<?php
/**
 * Generated by amphtml-update.py - do not edit.
 *
 * This is a list of error codes from the AMP specification. Note that 
 * tag names have been converted to lowercase.
 *
 * phpcs:ignoreFile
 */
class AMP_Error_Codes_Generated {

	private static $spec_file_revision = 1022;
	private static $minimum_validator_revision_required = 375;

	const UNKNOWN_CODE = 'Unknown error.';
	const INVALID_DOCTYPE_HTML = 'Invalid or missing doctype declaration. Should be <!doctype html>. See https://amp.dev/documentation/guides-and-tutorials/start/create/basic_markup/';
	const MANDATORY_TAG_MISSING = 'The mandatory tag \'%1\' is missing or incorrect.';
	const TAG_REQUIRED_BY_MISSING = 'The tag \'%1\' is missing or incorrect, but required by \'%2\'.';
	const WARNING_TAG_REQUIRED_BY_MISSING = 'The tag \'%1\' is missing or incorrect, but required by \'%2\'. This will soon be an error.';
	const TAG_EXCLUDED_BY_TAG = 'The tag \'%1\' is present, but is excluded by the presence of \'%2\'.';
	const WARNING_EXTENSION_UNUSED = 'The extension \'%1\' was found on this page, but is unused (no \'%2\' tag seen). This may become an error in the future.';
	const EXTENSION_UNUSED = 'The extension \'%1\' was found on this page, but is unused. Please remove this extension.';
	const WARNING_EXTENSION_DEPRECATED_VERSION = 'The extension \'%1\' is referenced at version \'%2\' which is a deprecated version. Please use a more recent version of this extension. This may become an error in the future.';
	const NON_LTS_SCRIPT_AFTER_LTS = '\'%1\' must use the LTS version to correspond with the first script in the page, which uses LTS.';
	const LTS_SCRIPT_AFTER_NON_LTS = '\'%1\' must use the non-LTS version to correspond with the first script in the page, which does not use LTS.';
	const ATTR_REQUIRED_BUT_MISSING = 'The attribute \'%1\' in tag \'%2\' is missing or incorrect, but required by attribute \'%3\'.';
	const DISALLOWED_TAG = 'The tag \'%1\' is disallowed.';
	const GENERAL_DISALLOWED_TAG = 'The tag \'%1\' is disallowed except in specific forms.';
	const DISALLOWED_SCRIPT_TAG = 'Custom JavaScript is not allowed.';
	const DISALLOWED_ATTR = 'The attribute \'%1\' may not appear in tag \'%2\'.';
	const DISALLOWED_STYLE_ATTR = 'The inline \'style\' attribute is not allowed in AMP documents. Use \'style amp-custom\' tag instead.';
	const INVALID_ATTR_VALUE = 'The attribute \'%1\' in tag \'%2\' is set to the invalid value \'%3\'.';
	const DUPLICATE_ATTRIBUTE = 'The tag \'%1\' contains the attribute \'%2\' repeated multiple times.';
	const ATTR_VALUE_REQUIRED_BY_LAYOUT = 'Invalid value \'%1\' for attribute \'%2\' in tag \'%3\' - for layout \'%4\', set the attribute \'%2\' to value \'%5\'.';
	const MISSING_LAYOUT_ATTRIBUTES = 'Incomplete layout attributes specified for tag \'%1\'. For example, provide attributes \'width\' and \'height\'.';
	const IMPLIED_LAYOUT_INVALID = 'The implied layout \'%1\' is not supported by tag \'%2\'.';
	const SPECIFIED_LAYOUT_INVALID = 'The specified layout \'%1\' is not supported by tag \'%2\'.';
	const MANDATORY_ATTR_MISSING = 'The mandatory attribute \'%1\' is missing in tag \'%2\'.';
	const INCONSISTENT_UNITS_FOR_WIDTH_AND_HEIGHT = 'Inconsistent units for width and height in tag \'%1\' - width is specified in \'%2\' whereas height is specified in \'%3\'.';
	const STYLESHEET_TOO_LONG = 'The author stylesheet specified in tag \'%1\' is too long - document contains %2 bytes whereas the limit is %3 bytes.';
	const STYLESHEET_AND_INLINE_STYLE_TOO_LONG = 'The author stylesheet specified in tag \'style amp-custom\' and the combined inline styles is too large - document contains %1 bytes whereas the limit is %2 bytes.';
	const INLINE_STYLE_TOO_LONG = 'The inline style specified in tag \'%1\' is too long - it contains %2 bytes whereas the limit is %3 bytes.';
	const MANDATORY_CDATA_MISSING_OR_INCORRECT = 'The mandatory text inside tag \'%1\' is missing or incorrect.';
	const CDATA_VIOLATES_BLACKLIST = 'The text inside tag \'%1\' contains \'%2\', which is disallowed.';
	const NON_WHITESPACE_CDATA_ENCOUNTERED = 'The tag \'%1\' contains text, which is disallowed.';
	const INVALID_JSON_CDATA = 'The script tag contains invalid JSON that cannot be parsed.';
	const DISALLOWED_PROPERTY_IN_ATTR_VALUE = 'The property \'%1\' in attribute \'%2\' in tag \'%3\' is disallowed.';
	const INVALID_PROPERTY_VALUE_IN_ATTR_VALUE = 'The property \'%1\' in attribute \'%2\' in tag \'%3\' is set to \'%4\', which is invalid.';
	const DUPLICATE_DIMENSION = 'Multiple image candidates with the same width or pixel density found in attribute \'%1\' in tag \'%2\'.';
	const MISSING_URL = 'Missing URL for attribute \'%1\' in tag \'%2\'.';
	const INVALID_URL = 'Malformed URL \'%3\' for attribute \'%1\' in tag \'%2\'.';
	const INVALID_URL_PROTOCOL = 'Invalid URL protocol \'%3:\' for attribute \'%1\' in tag \'%2\'.';
	const DISALLOWED_DOMAIN = 'The domain \'%3\' for attribute \'%1\' in tag \'%2\' is disallowed.';
	const DISALLOWED_RELATIVE_URL = 'The relative URL \'%3\' for attribute \'%1\' in tag \'%2\' is disallowed.';
	const MANDATORY_PROPERTY_MISSING_FROM_ATTR_VALUE = 'The property \'%1\' is missing from attribute \'%2\' in tag \'%3\'.';
	const UNESCAPED_TEMPLATE_IN_ATTR_VALUE = 'The attribute \'%1\' in tag \'%2\' is set to \'%3\', which contains unescaped Mustache template syntax.';
	const TEMPLATE_PARTIAL_IN_ATTR_VALUE = 'The attribute \'%1\' in tag \'%2\' is set to \'%3\', which contains a Mustache template partial.';
	const DEPRECATED_TAG = 'The tag \'%1\' is deprecated - use \'%2\' instead.';
	const DEPRECATED_ATTR = 'The attribute \'%1\' in tag \'%2\' is deprecated - use \'%3\' instead.';
	const MUTUALLY_EXCLUSIVE_ATTRS = 'Mutually exclusive attributes encountered in tag \'%1\' - pick one of %2.';
	const MANDATORY_ONEOF_ATTR_MISSING = 'The tag \'%1\' is missing a mandatory attribute - pick one of %2.';
	const MANDATORY_ANYOF_ATTR_MISSING = 'The tag \'%1\' is missing a mandatory attribute - pick at least one of %2.';
	const WRONG_PARENT_TAG = 'The parent tag of tag \'%1\' is \'%2\', but it can only be \'%3\'.';
	const DISALLOWED_TAG_ANCESTOR = 'The tag \'%1\' may not appear as a descendant of tag \'%2\'.';
	const MANDATORY_TAG_ANCESTOR = 'The tag \'%1\' may only appear as a descendant of tag \'%2\'.';
	const MANDATORY_TAG_ANCESTOR_WITH_HINT = 'The tag \'%1\' may only appear as a descendant of tag \'%2\'. Did you mean \'%3\'?';
	const DUPLICATE_UNIQUE_TAG = 'The tag \'%1\' appears more than once in the document.';
	const DUPLICATE_UNIQUE_TAG_WARNING = 'The tag \'%1\' appears more than once in the document. This will soon be an error.';
	const TEMPLATE_IN_ATTR_NAME = 'Mustache template syntax in attribute name \'%1\' in tag \'%2\'.';
	const ATTR_DISALLOWED_BY_IMPLIED_LAYOUT = 'The attribute \'%1\' in tag \'%2\' is disallowed by implied layout \'%3\'.';
	const ATTR_DISALLOWED_BY_SPECIFIED_LAYOUT = 'The attribute \'%1\' in tag \'%2\' is disallowed by specified layout \'%3\'.';
	const INCORRECT_NUM_CHILD_TAGS = 'Tag \'%1\' must have %2 child tags - saw %3 child tags.';
	const INCORRECT_MIN_NUM_CHILD_TAGS = 'Tag \'%1\' must have a minimum of %2 child tags - saw %3 child tags.';
	const TAG_NOT_ALLOWED_TO_HAVE_SIBLINGS = 'Tag \'%1\' is not allowed to have any sibling tags (\'%2\' should only have 1 child).';
	const MANDATORY_LAST_CHILD_TAG = 'Tag \'%1\', if present, must be the last child of tag \'%2\'.';
	const DISALLOWED_CHILD_TAG_NAME = 'Tag \'%1\' is disallowed as child of tag \'%2\'. Child tag must be one of %3.';
	const DISALLOWED_FIRST_CHILD_TAG_NAME = 'Tag \'%1\' is disallowed as first child of tag \'%2\'. First child tag must be one of %3.';
	const DISALLOWED_MANUFACTURED_BODY = 'Tag or text which is only allowed inside the body section found outside of the body section.';
	const CHILD_TAG_DOES_NOT_SATISFY_REFERENCE_POINT = 'The tag \'%1\', a child tag of \'%2\', does not satisfy one of the acceptable reference points: %3.';
	const CHILD_TAG_DOES_NOT_SATISFY_REFERENCE_POINT_SINGULAR = 'The tag \'%1\', a child tag of \'%2\', does not satisfy the reference point \'%3\'.';
	const MANDATORY_REFERENCE_POINT_MISSING = 'The mandatory reference point \'%1\' for \'%2\' is missing.';
	const DUPLICATE_REFERENCE_POINT = 'The reference point \'%1\' for \'%2\' must be unique but a duplicate was encountered.';
	const TAG_REFERENCE_POINT_CONFLICT = 'The tag \'%1\' conflicts with reference point \'%2\' because both define reference points.';
	const BASE_TAG_MUST_PRECEED_ALL_URLS = 'The tag \'%1\', which contains URLs, was found earlier in the document than the BASE element.';
	const MISSING_REQUIRED_EXTENSION = 'The tag \'%1\' requires including the \'%2\' extension JavaScript.';
	const ATTR_MISSING_REQUIRED_EXTENSION = 'The attribute \'%1\' requires including the \'%2\' extension JavaScript.';
	const DOCUMENT_TOO_COMPLEX = 'The document is too complex.';
	const INVALID_UTF8 = 'The document contains invalid UTF8.';
	const CSS_SYNTAX_INVALID_AT_RULE = 'CSS syntax error in tag \'%1\' - saw invalid at rule \'@%2\'.';
	const CSS_SYNTAX_STRAY_TRAILING_BACKSLASH = 'CSS syntax error in tag \'%1\' - stray trailing backslash.';
	const CSS_SYNTAX_UNTERMINATED_COMMENT = 'CSS syntax error in tag \'%1\' - unterminated comment.';
	const CSS_SYNTAX_UNTERMINATED_STRING = 'CSS syntax error in tag \'%1\' - unterminated string.';
	const CSS_SYNTAX_BAD_URL = 'CSS syntax error in tag \'%1\' - bad url.';
	const CSS_SYNTAX_EOF_IN_PRELUDE_OF_QUALIFIED_RULE = 'CSS syntax error in tag \'%1\' - end of stylesheet encountered in prelude of a qualified rule.';
	const CSS_SYNTAX_INVALID_PROPERTY = 'CSS syntax error in tag \'%1\' - invalid property \'%2\'. The only allowed properties are \'%3\'.';
	const CSS_SYNTAX_INVALID_PROPERTY_NOLIST = 'CSS syntax error in tag \'%1\' - invalid property \'%2\'.';
	const CSS_SYNTAX_QUALIFIED_RULE_HAS_NO_DECLARATIONS = 'CSS syntax error in tag \'%1\' - qualified rule \'%2\' has no declarations.';
	const CSS_SYNTAX_DISALLOWED_QUALIFIED_RULE_MUST_BE_INSIDE_KEYFRAME = 'CSS syntax error in tag \'%1\' - qualified rule \'%2\' must be located inside of a keyframe.';
	const CSS_SYNTAX_DISALLOWED_KEYFRAME_INSIDE_KEYFRAME = 'CSS syntax error in tag \'%1\' - keyframe inside keyframe is not allowed.';
	const CSS_SYNTAX_INVALID_DECLARATION = 'CSS syntax error in tag \'%1\' - invalid declaration.';
	const CSS_SYNTAX_INCOMPLETE_DECLARATION = 'CSS syntax error in tag \'%1\' - incomplete declaration.';
	const CSS_SYNTAX_ERROR_IN_PSEUDO_SELECTOR = 'CSS syntax error in tag \'%1\' - invalid pseudo selector.';
	const CSS_SYNTAX_MISSING_SELECTOR = 'CSS syntax error in tag \'%1\' - missing selector.';
	const CSS_SYNTAX_NOT_A_SELECTOR_START = 'CSS syntax error in tag \'%1\' - not a selector start.';
	const CSS_SYNTAX_UNPARSED_INPUT_REMAINS_IN_SELECTOR = 'CSS syntax error in tag \'%1\' - unparsed input remains in selector.';
	const CSS_SYNTAX_MISSING_URL = 'CSS syntax error in tag \'%1\' - missing url.';
	const CSS_SYNTAX_INVALID_URL = 'CSS syntax error in tag \'%1\' - invalid url \'%2\'.';
	const CSS_SYNTAX_INVALID_URL_PROTOCOL = 'CSS syntax error in tag \'%1\' - invalid url protocol \'%2:\'.';
	const CSS_SYNTAX_DISALLOWED_DOMAIN = 'CSS syntax error in tag \'%1\' - invalid domain \'%2\'.';
	const CSS_SYNTAX_DISALLOWED_RELATIVE_URL = 'CSS syntax error in tag \'%1\' - disallowed relative url \'%2\'.';
	const CSS_SYNTAX_INVALID_ATTR_SELECTOR = 'CSS syntax error in tag \'%1\' - invalid attribute selector.';
	const CSS_SYNTAX_DISALLOWED_PROPERTY_VALUE = 'CSS syntax error in tag \'%1\' - the property \'%2\' is set to the disallowed value \'%3\'.';
	const CSS_SYNTAX_DISALLOWED_PROPERTY_VALUE_WITH_HINT = 'CSS syntax error in tag \'%1\' - the property \'%2\' is set to the disallowed value \'%3\'. Allowed values: %4.';
	const CSS_SYNTAX_PROPERTY_DISALLOWED_WITHIN_AT_RULE = 'CSS syntax error in tag \'%1\' - the property \'%2\' is disallowed within @%3. Allowed properties: %4.';
	const CSS_SYNTAX_PROPERTY_DISALLOWED_TOGETHER_WITH = 'CSS syntax error in tag \'%1\' - the property \'%2\' is disallowed together with \'%3\'. Allowed properties: %4.';
	const CSS_SYNTAX_PROPERTY_REQUIRES_QUALIFICATION = 'CSS syntax error in tag \'%1\' - the property \'%2\' is disallowed unless the enclosing rule is prefixed with the \'%3\' qualification.';
	const CSS_SYNTAX_MALFORMED_MEDIA_QUERY = 'CSS syntax error in tag \'%1\' - malformed media query.';
	const CSS_SYNTAX_DISALLOWED_MEDIA_TYPE = 'CSS syntax error in tag \'%1\' - disallowed media type \'%2\'.';
	const CSS_SYNTAX_DISALLOWED_MEDIA_FEATURE = 'CSS syntax error in tag \'%1\' - disallowed media feature \'%2\'.';
	const CSS_EXCESSIVELY_NESTED = 'CSS excessively nested in tag \'%1\'.';
	const DOCUMENT_SIZE_LIMIT_EXCEEDED = 'Document exceeded %1 bytes limit. Actual size %2 bytes.';
	const VALUE_SET_MISMATCH = 'Attribute \'%1\' in tag \'%2\' contains a value that does not match any other tags on the page.';
	const DEV_MODE_ONLY = 'Tag \'html\' marked with attribute \'data-ampdevmode\'. Validator will suppress errors regarding any other tag with this attribute.';

}
