<?php // phpcs:disable Squiz.Commenting.FileComment.Missing
// phpcs:disable WordPress.Arrays.ArrayIndentation
// phpcs:disable WordPress.WhiteSpace.PrecisionAlignment
// phpcs:disable WordPress.Arrays.ArrayDeclarationSpacing
// phpcs:disable Generic.WhiteSpace.DisallowSpaceIndent
// phpcs:disable Generic.Arrays.DisallowLongArraySyntax
// phpcs:disable Squiz.Commenting.FileComment.Missing
// phpcs:disable Generic.Files.EndFileNewline
// phpcs:disable WordPress.Arrays.MultipleStatementAlignment

// NOTICE: This file was auto-generated with: npm run update-ecosystem-files.
return array (
  0 => 
  array (
    'name' => 'Podcast Player &#8211; Your Podcasting Companion',
    'slug' => 'podcast-player',
    'version' => '5.2.2',
    'author' => '<a href="https://www.vedathemes.com">vedathemes</a>',
    'author_profile' => 'https://profiles.wordpress.org/vedathemes',
    'requires' => '4.9',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 98,
    'ratings' => 
    array (
      1 => 0,
      2 => 1,
      3 => 0,
      4 => 2,
      5 => 46,
    ),
    'num_ratings' => 49,
    'support_threads' => 6,
    'support_threads_resolved' => 6,
    'active_installs' => 8000,
    'downloaded' => 128848,
    'last_updated' => '2021-10-14 9:56am GMT',
    'added' => '2019-02-06',
    'homepage' => 'https://vedathemes.com/podcast-player/',
    'short_description' => 'Showcase your podcast only using podcasting feed url. Use custom widget, shortcode or editor block&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/podcast-player.5.2.2.zip',
    'tags' => 
    array (
      'feed-to-audio' => 'feed to audio',
      'podcast' => 'podcast',
      'podcaster' => 'podcaster',
      'podcasting' => 'podcasting',
      'rss-feed' => 'rss feed',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/podcast-player/assets/icon-256x256.png?rev=2025683',
      '2x' => 'https://ps.w.org/podcast-player/assets/icon-256x256.png?rev=2025683',
    ),
    'wporg' => true,
  ),
  1 => 
  array (
    'name' => 'WPSSO Schema JSON-LD Markup',
    'slug' => 'wpsso-schema-json-ld',
    'version' => '5.1.0',
    'author' => '<a href="https://wpsso.com/">JS Morisset</a>',
    'author_profile' => 'https://profiles.wordpress.org/jsmoriss',
    'requires' => '5.0',
    'tested' => '5.8.1',
    'requires_php' => '7.0',
    'rating' => 90,
    'ratings' => 
    array (
      1 => 5,
      2 => 2,
      3 => 1,
      4 => 1,
      5 => 55,
    ),
    'num_ratings' => 64,
    'support_threads' => 4,
    'support_threads_resolved' => 4,
    'active_installs' => 4000,
    'downloaded' => 291598,
    'last_updated' => '2021-10-19 3:30pm GMT',
    'added' => '2016-02-14',
    'homepage' => 'https://wpsso.com/extend/plugins/wpsso-schema-json-ld/',
    'short_description' => 'Discontinued / deprecated add-on: The features of this plugin were merged into WPSSO Core v9.0.0.',
    'download_link' => 'https://downloads.wordpress.org/plugin/wpsso-schema-json-ld.zip',
    'tags' => 
    array (
    ),
    'donate_link' => '',
    'icons' => 
    array (
      'default' => 'https://s.w.org/plugins/geopattern-icon/wpsso-schema-json-ld.svg',
    ),
    'wporg' => true,
  ),
  2 => 
  array (
    'name' => 'ShortPixel Image Optimizer',
    'slug' => 'shortpixel-image-optimiser',
    'version' => '4.22.6',
    'author' => '<a href="https://shortpixel.com">ShortPixel</a>',
    'author_profile' => 'https://profiles.wordpress.org/shortpixel',
    'requires' => '4.2.0',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 92,
    'ratings' => 
    array (
      1 => 53,
      2 => 12,
      3 => 8,
      4 => 12,
      5 => 546,
    ),
    'num_ratings' => 631,
    'support_threads' => 11,
    'support_threads_resolved' => 7,
    'active_installs' => 300000,
    'downloaded' => 7108264,
    'last_updated' => '2021-10-11 2:44pm GMT',
    'added' => '2014-11-05',
    'homepage' => 'https://shortpixel.com/',
    'short_description' => 'Speed up your website &amp; boost your SEO by compressing old &amp; new images and PDFs. Optimize and convert WebP &amp; AVIF.',
    'download_link' => 'https://downloads.wordpress.org/plugin/shortpixel-image-optimiser.4.22.6.zip',
    'tags' => 
    array (
      'compressor' => 'compressor',
      'convert-webp' => 'convert webp',
      'image-optimization' => 'image optimization',
      'optimize-images' => 'optimize images',
      'resize' => 'resize',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/shortpixel-image-optimiser/assets/icon-128x128.png?rev=1038819',
      '2x' => 'https://ps.w.org/shortpixel-image-optimiser/assets/icon-256x256.png?rev=1038819',
    ),
    'wporg' => true,
  ),
  3 => 
  array (
    'name' => 'Theme Kit for Twenty Twenty-One &amp; Twenty Twenty (Customization, Gutenberg Blocks, Templates) – Twentig',
    'slug' => 'twentig',
    'version' => '1.3.6',
    'author' => '<a href="https://twentig.com">Twentig</a>',
    'author_profile' => 'https://profiles.wordpress.org/twentig',
    'requires' => '5.5',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 100,
    'ratings' => 
    array (
      1 => 0,
      2 => 0,
      3 => 0,
      4 => 2,
      5 => 110,
    ),
    'num_ratings' => 112,
    'support_threads' => 39,
    'support_threads_resolved' => 30,
    'active_installs' => 10000,
    'downloaded' => 151982,
    'last_updated' => '2021-09-15 2:23pm GMT',
    'added' => '2019-05-29',
    'homepage' => 'https://twentig.com',
    'short_description' => 'Supercharge your WordPress theme (Twenty Twenty-One &amp; Twenty Twenty) with customization options, enhanced Gutenberg blocks,&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/twentig.1.3.6.zip',
    'tags' => 
    array (
      'gutenberg' => 'gutenberg',
      'gutenberg-blocks' => 'gutenberg blocks',
      'templates' => 'templates',
      'theme' => 'theme',
      'twenty-twenty-one' => 'twenty-twenty-one',
    ),
    'donate_link' => 'https://www.paypal.com/donate?hosted_button_id=JTBTPQAFEA94E',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/twentig/assets/icon.svg?rev=2569439',
      '2x' => 'https://ps.w.org/twentig/assets/icon-256x256.png?rev=2569439',
      'svg' => 'https://ps.w.org/twentig/assets/icon.svg?rev=2569439',
    ),
    'wporg' => true,
  ),
  4 => 
  array (
    'name' => 'Custom Post Type UI',
    'slug' => 'custom-post-type-ui',
    'version' => '1.10.0',
    'author' => '<a href="https://webdevstudios.com/">WebDevStudios</a>',
    'author_profile' => 'https://profiles.wordpress.org/williamsba1',
    'requires' => '5.5',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 94,
    'ratings' => 
    array (
      1 => 12,
      2 => 3,
      3 => 6,
      4 => 9,
      5 => 205,
    ),
    'num_ratings' => 235,
    'support_threads' => 57,
    'support_threads_resolved' => 28,
    'active_installs' => 1000000,
    'downloaded' => 9061699,
    'last_updated' => '2021-10-05 1:54am GMT',
    'added' => '2010-02-26',
    'homepage' => 'https://github.com/WebDevStudios/custom-post-type-ui/',
    'short_description' => 'Admin UI for creating custom post types and custom taxonomies for WordPress',
    'download_link' => 'https://downloads.wordpress.org/plugin/custom-post-type-ui.1.10.0.zip',
    'tags' => 
    array (
      'cms' => 'cms',
      'cpt' => 'cpt',
      'custom-post-types' => 'custom post types',
      'post' => 'post',
      'types' => 'types',
    ),
    'donate_link' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3084056',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/custom-post-type-ui/assets/icon-128x128.png?rev=2549362',
      '2x' => 'https://ps.w.org/custom-post-type-ui/assets/icon-256x256.png?rev=2549362',
    ),
    'wporg' => true,
  ),
  5 => 
  array (
    'name' => 'Flex Posts &#8211; Widget and Gutenberg Block',
    'slug' => 'flex-posts',
    'version' => '1.8.1',
    'author' => '<a href="https://tajam.id/">Tajam</a>',
    'author_profile' => 'https://profiles.wordpress.org/tajam',
    'requires' => '5.2',
    'tested' => '5.8.1',
    'requires_php' => false,
    'rating' => 100,
    'ratings' => 
    array (
      1 => 0,
      2 => 0,
      3 => 0,
      4 => 0,
      5 => 17,
    ),
    'num_ratings' => 17,
    'support_threads' => 3,
    'support_threads_resolved' => 1,
    'active_installs' => 3000,
    'downloaded' => 25509,
    'last_updated' => '2021-07-29 10:41am GMT',
    'added' => '2018-05-10',
    'homepage' => 'https://tajam.id/flex-posts/',
    'short_description' => 'A widget to display posts with thumbnails in various layouts. Fits nicely in any widget area size.',
    'download_link' => 'https://downloads.wordpress.org/plugin/flex-posts.zip',
    'tags' => 
    array (
      'category-posts' => 'category posts',
      'grid' => 'grid',
      'magazine' => 'magazine',
      'news' => 'news',
      'responsive' => 'responsive',
    ),
    'donate_link' => 'https://tajam.id/',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/flex-posts/assets/icon-128x128.png?rev=1871802',
    ),
    'wporg' => true,
  ),
  6 => 
  array (
    'name' => 'YARPP &#8211; Yet Another Related Posts Plugin',
    'slug' => 'yet-another-related-posts-plugin',
    'version' => '5.27.6',
    'author' => '<a href="https://yarpp.com/">YARPP</a>',
    'author_profile' => 'https://profiles.wordpress.org/jeffparker',
    'requires' => '3.7',
    'tested' => '5.8.1',
    'requires_php' => '5.3',
    'rating' => 94,
    'ratings' => 
    array (
      1 => 33,
      2 => 2,
      3 => 14,
      4 => 45,
      5 => 653,
    ),
    'num_ratings' => 747,
    'support_threads' => 20,
    'support_threads_resolved' => 6,
    'active_installs' => 100000,
    'downloaded' => 6603700,
    'last_updated' => '2021-10-12 3:43pm GMT',
    'added' => '2008-01-02',
    'homepage' => 'https://yarpp.com/',
    'short_description' => 'The best WordPress plugin for displaying related posts. Simple and flexible, with a powerful proven&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/yet-another-related-posts-plugin.5.27.6.zip',
    'tags' => 
    array (
      'contextual-related-posts' => 'contextual related posts',
      'posts' => 'posts',
      'related-posts' => 'related posts',
      'seo' => 'seo',
      'similar-posts' => 'similar posts',
    ),
    'donate_link' => 'https://yarpp.com',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/yet-another-related-posts-plugin/assets/icon-128x128.png?rev=2549977',
      '2x' => 'https://ps.w.org/yet-another-related-posts-plugin/assets/icon-256x256.png?rev=2549977',
    ),
    'wporg' => true,
  ),
  7 => 
  array (
    'name' => 'Superb WordPress Table (SEO Optimized Tables With Schema)',
    'slug' => 'superb-tables',
    'version' => '1.0.9',
    'author' => '<a href="http://superbthemes.com">SuPlugins</a>',
    'author_profile' => 'https://profiles.wordpress.org/suplugins',
    'requires' => '3.0.1',
    'tested' => '5.8.1',
    'requires_php' => '5.2.4',
    'rating' => 86,
    'ratings' => 
    array (
      1 => 0,
      2 => 1,
      3 => 0,
      4 => 0,
      5 => 3,
    ),
    'num_ratings' => 4,
    'support_threads' => 1,
    'support_threads_resolved' => 1,
    'active_installs' => 4000,
    'downloaded' => 37357,
    'last_updated' => '2021-10-01 9:37am GMT',
    'added' => '2019-03-05',
    'homepage' => 'https://superbthemes.com/plugins/superb-tables/',
    'short_description' => 'Responsive &amp; SEO Optimized tables. Get your Google Featured Snippets. Different table designs, table shortcodes&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/superb-tables.1.0.9.zip',
    'tags' => 
    array (
      'content-tables' => 'content tables',
      'responsive-tables' => 'responsive tables',
      'table' => 'table',
      'tables' => 'tables',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/superb-tables/assets/icon-256x256.png?rev=2044672',
      '2x' => 'https://ps.w.org/superb-tables/assets/icon-256x256.png?rev=2044672',
    ),
    'wporg' => true,
  ),
  8 => 
  array (
    'name' => 'Floating Button',
    'slug' => 'floating-button',
    'version' => '5.1',
    'author' => '<a href="https://wow-estore.com/">Wow-Company</a>',
    'author_profile' => 'https://profiles.wordpress.org/wpcalc',
    'requires' => '3.2',
    'tested' => '5.8.1',
    'requires_php' => '5.3',
    'rating' => 80,
    'ratings' => 
    array (
      1 => 1,
      2 => 1,
      3 => 0,
      4 => 0,
      5 => 5,
    ),
    'num_ratings' => 7,
    'support_threads' => 1,
    'support_threads_resolved' => 0,
    'active_installs' => 2000,
    'downloaded' => 35836,
    'last_updated' => '2021-10-12 9:08am GMT',
    'added' => '2018-09-08',
    'homepage' => 'https://wordpress.org/plugins/floating-button/',
    'short_description' => 'Easily create a custom sticky floating buttons. The Floating Button will be the effective solution for increasing the recognition of your web resource',
    'download_link' => 'https://downloads.wordpress.org/plugin/floating-button.5.1.zip',
    'tags' => 
    array (
      'circle-menu' => 'circle menu',
      'float-menu' => 'float menu',
      'floating-button' => 'floating button',
      'floating-menu' => 'floating menu',
      'sticky-button' => 'sticky button',
    ),
    'donate_link' => 'https://wow-estore.com/item/floating-button-pro/',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/floating-button/assets/icon-128x128.png?rev=2533016',
      '2x' => 'https://ps.w.org/floating-button/assets/icon-256x256.png?rev=2533016',
    ),
    'wporg' => true,
  ),
  9 => 
  array (
    'name' => 'Breadcrumb NavXT',
    'slug' => 'breadcrumb-navxt',
    'version' => '6.6.0',
    'author' => '<a href="http://mtekk.us/">John Havlik</a>',
    'author_profile' => 'https://profiles.wordpress.org/mtekk',
    'requires' => '4.9',
    'tested' => '5.7.3',
    'requires_php' => '5.5',
    'rating' => 94,
    'ratings' => 
    array (
      1 => 5,
      2 => 2,
      3 => 4,
      4 => 7,
      5 => 104,
    ),
    'num_ratings' => 122,
    'support_threads' => 8,
    'support_threads_resolved' => 3,
    'active_installs' => 900000,
    'downloaded' => 10200481,
    'last_updated' => '2021-04-01 2:13am GMT',
    'added' => '2007-12-01',
    'homepage' => 'http://mtekk.us/code/breadcrumb-navxt/',
    'short_description' => 'Breadcrumb NavXT, the successor to the popular WordPress plugin Breadcrumb Navigation XT, was written from the ground up to be better than its ancesto &hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/breadcrumb-navxt.6.6.0.zip',
    'tags' => 
    array (
      'breadcrumb' => 'breadcrumb',
      'breadcrumbs' => 'breadcrumbs',
      'menu' => 'menu',
      'navigation' => 'navigation',
      'trail' => 'trail',
    ),
    'donate_link' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=FD5XEU783BR8U&lc=US&item_name=Breadcrumb%20NavXT%20Donation&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/breadcrumb-navxt/assets/icon.svg?rev=1927103',
      '2x' => 'https://ps.w.org/breadcrumb-navxt/assets/icon-256x256.png?rev=2410525',
      'svg' => 'https://ps.w.org/breadcrumb-navxt/assets/icon.svg?rev=1927103',
    ),
    'wporg' => true,
  ),
  10 => 
  array (
    'name' => 'WP Recipe Maker',
    'slug' => 'wp-recipe-maker',
    'version' => '7.6.1',
    'author' => '<a href="http://bootstrapped.ventures/">Bootstrapped Ventures</a>',
    'author_profile' => 'https://profiles.wordpress.org/brechtvds',
    'requires' => '4.4',
    'tested' => '5.8.1',
    'requires_php' => '5.4',
    'rating' => 100,
    'ratings' => 
    array (
      1 => 1,
      2 => 0,
      3 => 1,
      4 => 4,
      5 => 209,
    ),
    'num_ratings' => 215,
    'support_threads' => 21,
    'support_threads_resolved' => 16,
    'active_installs' => 50000,
    'downloaded' => 1589392,
    'last_updated' => '2021-09-16 11:33am GMT',
    'added' => '2016-09-07',
    'homepage' => 'http://bootstrapped.ventures/wp-recipe-maker/',
    'short_description' => 'The easy and user-friendly recipe plugin for everyone. Automatic JSON-LD metadata for food AND how-to recipes will improve your SEO!',
    'download_link' => 'https://downloads.wordpress.org/plugin/wp-recipe-maker.zip',
    'tags' => 
    array (
      'cooking' => 'cooking',
      'food' => 'food',
      'ingredients' => 'ingredients',
      'recipe' => 'Recipe',
      'recipes' => 'recipes',
    ),
    'donate_link' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QG7KZMGFU325Y',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/wp-recipe-maker/assets/icon-128x128.png?rev=1491788',
      '2x' => 'https://ps.w.org/wp-recipe-maker/assets/icon-256x256.png?rev=1491788',
    ),
    'wporg' => true,
  ),
  11 => 
  array (
    'name' => 'Slim SEO &#8211; Fast &amp; Automated WordPress SEO Plugin',
    'slug' => 'slim-seo',
    'version' => '3.10.2',
    'author' => '<a href="https://elightup.com">eLightUp</a>',
    'author_profile' => 'https://profiles.wordpress.org/rilwis',
    'requires' => '4.5',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 92,
    'ratings' => 
    array (
      1 => 1,
      2 => 3,
      3 => 0,
      4 => 0,
      5 => 27,
    ),
    'num_ratings' => 31,
    'support_threads' => 8,
    'support_threads_resolved' => 4,
    'active_installs' => 10000,
    'downloaded' => 180498,
    'last_updated' => '2021-09-27 6:47am GMT',
    'added' => '2018-12-31',
    'homepage' => 'https://wpslimseo.com',
    'short_description' => 'A full-featured SEO plugin for WordPress that&#039;s lightweight, blazing fast with minimum configuration. No bloats,&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/slim-seo.3.10.2.zip',
    'tags' => 
    array (
      'google' => 'google',
      'schema' => 'schema',
      'search-engine-optimization' => 'search engine optimization',
      'seo' => 'seo',
      'sitemap' => 'sitemap',
    ),
    'donate_link' => 'https://wpslimseo.com/pro/',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/slim-seo/assets/icon.svg?rev=2005049',
      'svg' => 'https://ps.w.org/slim-seo/assets/icon.svg?rev=2005049',
    ),
    'wporg' => true,
  ),
  12 => 
  array (
    'name' => 'Schema &amp; Structured Data for WP &amp; AMP',
    'slug' => 'schema-and-structured-data-for-wp',
    'version' => '1.9.86.1',
    'author' => '<a href="http://structured-data-for-wp.com/">Magazine3</a>',
    'author_profile' => 'https://profiles.wordpress.org/magazine3',
    'requires' => '3.0',
    'tested' => '5.8.1',
    'requires_php' => false,
    'rating' => 94,
    'ratings' => 
    array (
      1 => 13,
      2 => 1,
      3 => 2,
      4 => 10,
      5 => 184,
    ),
    'num_ratings' => 210,
    'support_threads' => 33,
    'support_threads_resolved' => 11,
    'active_installs' => 80000,
    'downloaded' => 2455590,
    'last_updated' => '2021-10-20 2:42am GMT',
    'added' => '2018-08-06',
    'homepage' => '',
    'short_description' => 'Schema &amp; Structured Data for WP &amp; AMP adds Google Rich Snippets markup according to&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/schema-and-structured-data-for-wp.1.9.86.1.zip',
    'tags' => 
    array (
      'google-snippets' => 'google snippets',
      'rich-snippets' => 'rich snippets',
      'schema' => 'schema',
      'schema-org' => 'schema.org',
      'structured-data' => 'structured data',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/schema-and-structured-data-for-wp/assets/icon-128x128.png?rev=1922284',
      '2x' => 'https://ps.w.org/schema-and-structured-data-for-wp/assets/icon-256x256.png?rev=1922284',
    ),
    'wporg' => true,
  ),
  13 => 
  array (
    'name' => 'GenerateBlocks',
    'slug' => 'generateblocks',
    'version' => '1.3.5',
    'author' => '<a href="https://tomusborne.com">Tom Usborne</a>',
    'author_profile' => 'https://profiles.wordpress.org/edge22',
    'requires' => '5.4',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 98,
    'ratings' => 
    array (
      1 => 0,
      2 => 0,
      3 => 2,
      4 => 1,
      5 => 72,
    ),
    'num_ratings' => 75,
    'support_threads' => 17,
    'support_threads_resolved' => 5,
    'active_installs' => 60000,
    'downloaded' => 255255,
    'last_updated' => '2021-07-19 6:12pm GMT',
    'added' => '2020-05-19',
    'homepage' => 'https://generateblocks.com',
    'short_description' => 'A small collection of lightweight WordPress blocks that can accomplish nearly anything.',
    'download_link' => 'https://downloads.wordpress.org/plugin/generateblocks.1.3.5.zip',
    'tags' => 
    array (
      'blocks' => 'blocks',
      'container' => 'container',
      'grid' => 'grid',
      'gutenberg' => 'gutenberg',
      'headline' => 'headline',
    ),
    'donate_link' => 'https://generateblocks.com',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/generateblocks/assets/icon-128x128.png?rev=2336822',
      '2x' => 'https://ps.w.org/generateblocks/assets/icon-256x256.png?rev=2336822',
    ),
    'wporg' => true,
  ),
  14 => 
  array (
    'name' => 'Blackhole for Bad Bots',
    'slug' => 'blackhole-bad-bots',
    'version' => '3.2',
    'author' => '<a href="https://plugin-planet.com/">Jeff Starr</a>',
    'author_profile' => 'https://profiles.wordpress.org/specialk',
    'requires' => '4.1',
    'tested' => '5.8.1',
    'requires_php' => '5.6.20',
    'rating' => 98,
    'ratings' => 
    array (
      1 => 2,
      2 => 0,
      3 => 3,
      4 => 2,
      5 => 108,
    ),
    'num_ratings' => 115,
    'support_threads' => 7,
    'support_threads_resolved' => 7,
    'active_installs' => 30000,
    'downloaded' => 311643,
    'last_updated' => '2021-07-19 8:41pm GMT',
    'added' => '2016-02-18',
    'homepage' => 'https://perishablepress.com/blackhole-bad-bots/',
    'short_description' => 'Blackhole is a WordPress security plugin that detects and traps bad bots in a virtual black hole, where they are denied access to your entire site.',
    'download_link' => 'https://downloads.wordpress.org/plugin/blackhole-bad-bots.3.2.zip',
    'tags' => 
    array (
      'anti-spam' => 'anti-spam',
      'bad-bots' => 'bad bots',
      'blackhole' => 'blackhole',
      'honeypot' => 'honeypot',
      'security' => 'security',
    ),
    'donate_link' => 'https://monzillamedia.com/donate.html',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/blackhole-bad-bots/assets/icon-128x128.png?rev=1471215',
      '2x' => 'https://ps.w.org/blackhole-bad-bots/assets/icon-256x256.png?rev=1471215',
    ),
    'wporg' => true,
  ),
  15 => 
  array (
    'name' => 'Page View Count',
    'slug' => 'page-views-count',
    'version' => '2.4.12',
    'author' => '<a href="https://a3rev.com">a3rev Software</a>',
    'author_profile' => 'https://profiles.wordpress.org/a3rev',
    'requires' => '5.0',
    'tested' => '5.8.1',
    'requires_php' => false,
    'rating' => 78,
    'ratings' => 
    array (
      1 => 8,
      2 => 5,
      3 => 2,
      4 => 3,
      5 => 30,
    ),
    'num_ratings' => 48,
    'support_threads' => 4,
    'support_threads_resolved' => 0,
    'active_installs' => 20000,
    'downloaded' => 407905,
    'last_updated' => '2021-07-19 10:48am GMT',
    'added' => '2012-12-21',
    'homepage' => '',
    'short_description' => 'Places an icon, all time views count and views today count at the bottom of&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/page-views-count.2.4.12.zip',
    'tags' => 
    array (
      'gutenberg' => 'gutenberg',
      'page-view-count' => 'page view count',
      'post-view-count' => 'post view count',
      'post-views' => 'post views',
      'wordpress-page-view' => 'wordpress page view',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/page-views-count/assets/icon.svg?rev=986301',
      '2x' => 'https://ps.w.org/page-views-count/assets/icon-256x256.png?rev=986301',
      'svg' => 'https://ps.w.org/page-views-count/assets/icon.svg?rev=986301',
    ),
    'wporg' => true,
  ),
  16 => 
  array (
    'name' => 'Newspack Listings',
    'slug' => 'newspack-listings',
    'homepage' => 'https://github.com/Automattic/newspack-listings/releases',
    'short_description' => '<p>Create reusable content as listings and add them to lists wherever core blocks can be used</p>
',
    'icons' => 
    array (
      '1x' => 'https://amp-wp.org/wp-content/uploads/2021/02/listings2-285x160.jpg',
      '2x' => 'https://amp-wp.org/wp-content/uploads/2021/02/listings2-372x209.jpg',
      'svg' => '',
    ),
    'wporg' => false,
  ),
  17 => 
  array (
    'name' => 'Newspack Newsletters',
    'slug' => 'newspack-newsletters',
    'version' => '1.34.0',
    'author' => 'Automattic',
    'author_profile' => 'https://profiles.wordpress.org/automattic',
    'requires' => '5.3',
    'tested' => '5.8.0',
    'requires_php' => '5.6',
    'rating' => 0,
    'ratings' => 
    array (
      1 => 0,
      2 => 0,
      3 => 0,
      4 => 0,
      5 => 0,
    ),
    'num_ratings' => 0,
    'support_threads' => 1,
    'support_threads_resolved' => 1,
    'active_installs' => 600,
    'downloaded' => 3484,
    'last_updated' => '2021-10-19 8:03pm GMT',
    'added' => '2021-02-15',
    'homepage' => 'https://newspack.pub',
    'short_description' => 'Create email newsletters with the Gutenberg editor and distribute them with your Mailchimp or Constant Contact mailing lists.',
    'download_link' => 'https://downloads.wordpress.org/plugin/newspack-newsletters.zip',
    'tags' => 
    array (
      'constant-contact' => 'constant contact',
      'mailchimp' => 'mailchimp',
      'newsletters' => 'newsletters',
      'newspack' => 'Newspack',
      'wordpress-com' => 'WordPress.com',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/newspack-newsletters/assets/icon.svg?rev=2475195',
      '2x' => 'https://ps.w.org/newspack-newsletters/assets/icon-256x256.png?rev=2475195',
      'svg' => 'https://ps.w.org/newspack-newsletters/assets/icon.svg?rev=2475195',
    ),
    'wporg' => true,
  ),
  18 => 
  array (
    'name' => 'Web Stories',
    'slug' => 'web-stories',
    'version' => '1.13.0',
    'author' => '<a href="https://opensource.google.com/">Google</a>',
    'author_profile' => 'https://profiles.wordpress.org/google',
    'requires' => '5.5',
    'tested' => '5.8.1',
    'requires_php' => '7.0',
    'rating' => 86,
    'ratings' => 
    array (
      1 => 5,
      2 => 2,
      3 => 2,
      4 => 4,
      5 => 33,
    ),
    'num_ratings' => 46,
    'support_threads' => 133,
    'support_threads_resolved' => 99,
    'active_installs' => 30000,
    'downloaded' => 383025,
    'last_updated' => '2021-10-12 10:17pm GMT',
    'added' => '2020-09-22',
    'homepage' => 'https://wp.stories.google/',
    'short_description' => 'Web Stories are a visual storytelling format for the open web which immerses your readers&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/web-stories.1.13.0.zip',
    'tags' => 
    array (
      'amp' => 'amp',
      'google' => 'google',
      'stories' => 'stories',
      'storytelling' => 'storytelling',
      'web-stories' => 'web stories',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/web-stories/assets/icon.svg?rev=2386543',
      '2x' => 'https://ps.w.org/web-stories/assets/icon-256x256.png?rev=2386543',
      'svg' => 'https://ps.w.org/web-stories/assets/icon.svg?rev=2386543',
    ),
    'wporg' => true,
  ),
  19 => 
  array (
    'name' => 'Jetpack &#8211; WP Security, Backup, Speed, &amp; Growth',
    'slug' => 'jetpack',
    'version' => '10.2.1',
    'author' => '<a href="https://jetpack.com">Automattic</a>',
    'author_profile' => 'https://profiles.wordpress.org/automattic',
    'requires' => '5.7',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 78,
    'ratings' => 
    array (
      1 => 321,
      2 => 80,
      3 => 82,
      4 => 138,
      5 => 1030,
    ),
    'num_ratings' => 1651,
    'support_threads' => 304,
    'support_threads_resolved' => 268,
    'active_installs' => 5000000,
    'downloaded' => 249931352,
    'last_updated' => '2021-10-19 3:50pm GMT',
    'added' => '2011-01-20',
    'homepage' => 'https://jetpack.com',
    'short_description' => 'Improve your WP security with powerful one-click tools like backup and malware scan. Get essential free tools including stats, CDN and social sharing.',
    'download_link' => 'https://downloads.wordpress.org/plugin/jetpack.10.2.1.zip',
    'tags' => 
    array (
      'backup' => 'backup',
      'malware' => 'malware',
      'scan' => 'scan',
      'security' => 'security',
      'woo' => 'woo',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/jetpack/assets/icon.svg?rev=2394525',
      '2x' => 'https://ps.w.org/jetpack/assets/icon-256x256.png?rev=2394525',
      'svg' => 'https://ps.w.org/jetpack/assets/icon.svg?rev=2394525',
    ),
    'wporg' => true,
  ),
  20 => 
  array (
    'name' => 'Easy Notification Bar',
    'slug' => 'easy-notification-bar',
    'version' => '1.4.3',
    'author' => '<a href="https://www.wpexplorer.com/">WPExplorer</a>',
    'author_profile' => 'https://profiles.wordpress.org/wpexplorer',
    'requires' => '5.2.0',
    'tested' => '5.8.1',
    'requires_php' => '5.6.2',
    'rating' => 82,
    'ratings' => 
    array (
      1 => 0,
      2 => 1,
      3 => 1,
      4 => 1,
      5 => 4,
    ),
    'num_ratings' => 7,
    'support_threads' => 5,
    'support_threads_resolved' => 3,
    'active_installs' => 4000,
    'downloaded' => 38293,
    'last_updated' => '2021-09-28 3:14am GMT',
    'added' => '2019-06-20',
    'homepage' => 'https://wordpress.org/plugins/easy-notification-bar/',
    'short_description' => 'Easily add a custom top bar notification message to on your site with live customization options via the WordPress customizer.',
    'download_link' => 'https://downloads.wordpress.org/plugin/easy-notification-bar.zip',
    'tags' => 
    array (
      'notice' => 'notice',
      'notice-bar' => 'notice bar',
      'notification' => 'notification',
      'notification-bar' => 'notification bar',
      'top-bar' => 'top bar',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/easy-notification-bar/assets/icon-128x128.png?rev=2515988',
      '2x' => 'https://ps.w.org/easy-notification-bar/assets/icon-256x256.png?rev=2515988',
    ),
    'wporg' => true,
  ),
  21 => 
  array (
    'name' => 'Antispam Bee',
    'slug' => 'antispam-bee',
    'version' => '2.10.0',
    'author' => '<a href="https://pluginkollektiv.org">pluginkollektiv</a>',
    'author_profile' => 'https://profiles.wordpress.org/pluginkollektiv',
    'requires' => '4.5',
    'tested' => '5.8.1',
    'requires_php' => '5.2',
    'rating' => 96,
    'ratings' => 
    array (
      1 => 7,
      2 => 1,
      3 => 1,
      4 => 2,
      5 => 174,
    ),
    'num_ratings' => 185,
    'support_threads' => 6,
    'support_threads_resolved' => 6,
    'active_installs' => 700000,
    'downloaded' => 5137226,
    'last_updated' => '2021-07-29 11:15am GMT',
    'added' => '2009-01-10',
    'homepage' => 'https://antispambee.pluginkollektiv.org/',
    'short_description' => 'Antispam plugin with a sophisticated tool set for effective day to day comment and trackback spam-fighting. Build with data protection and privacy in  &hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/antispam-bee.2.10.0.zip',
    'tags' => 
    array (
      'anti-spam' => 'anti-spam',
      'antispam' => 'antispam',
      'block-spam' => 'block spam',
      'comment' => 'comment',
      'comments' => 'comments',
    ),
    'donate_link' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=TD4AMD2D8EMZW',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/antispam-bee/assets/icon-128x128.png?rev=977629',
      '2x' => 'https://ps.w.org/antispam-bee/assets/icon-256x256.png?rev=977629',
    ),
    'wporg' => true,
  ),
  22 => 
  array (
    'name' => 'SimpleTOC &#8211; Table of Contents Block',
    'slug' => 'simpletoc',
    'version' => '4.8',
    'author' => '<a href="https://marc.tv">Marc Tönsing</a>',
    'author_profile' => 'https://profiles.wordpress.org/marcdk',
    'requires' => '5.0',
    'tested' => '5.8.1',
    'requires_php' => false,
    'rating' => 100,
    'ratings' => 
    array (
      1 => 0,
      2 => 0,
      3 => 0,
      4 => 0,
      5 => 24,
    ),
    'num_ratings' => 24,
    'support_threads' => 5,
    'support_threads_resolved' => 4,
    'active_installs' => 2000,
    'downloaded' => 22174,
    'last_updated' => '2021-07-29 9:07pm GMT',
    'added' => '2020-04-14',
    'homepage' => 'https://marc.tv/simpletoc-wordpress-inhaltsverzeichnis-plugin-gutenberg/',
    'short_description' => 'Adds a custom Table of Contents Gutenberg block.',
    'download_link' => 'https://downloads.wordpress.org/plugin/simpletoc.4.8.zip',
    'tags' => 
    array (
      'amp' => 'amp',
      'block' => 'block',
      'gutenberg' => 'gutenberg',
      'table-of-contents' => 'table of contents',
      'toc' => 'toc',
    ),
    'donate_link' => 'https://marc.tv/out/donate',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/simpletoc/assets/icon.svg?rev=2451408',
      '2x' => 'https://ps.w.org/simpletoc/assets/icon-256x256.png?rev=2451408',
      'svg' => 'https://ps.w.org/simpletoc/assets/icon.svg?rev=2451408',
    ),
    'wporg' => true,
  ),
  23 => 
  array (
    'name' => 'Log in with Google',
    'slug' => 'login-with-google',
    'version' => '1.2.1',
    'author' => '<a href="https://rtcamp.com">rtCamp</a>',
    'author_profile' => 'https://profiles.wordpress.org/rtcamp',
    'requires' => '5.4.2',
    'tested' => '5.7.3',
    'requires_php' => '7.3',
    'rating' => 100,
    'ratings' => 
    array (
      1 => 0,
      2 => 0,
      3 => 0,
      4 => 0,
      5 => 6,
    ),
    'num_ratings' => 6,
    'support_threads' => 2,
    'support_threads_resolved' => 0,
    'active_installs' => 400,
    'downloaded' => 3450,
    'last_updated' => '2021-07-23 10:00pm GMT',
    'added' => '2020-10-01',
    'homepage' => '',
    'short_description' => 'Minimal plugin that allows WordPress users to log in using Google.',
    'download_link' => 'https://downloads.wordpress.org/plugin/login-with-google.1.2.1.zip',
    'tags' => 
    array (
      'authentication' => 'authentication',
      'google-login' => 'Google Login',
      'oauth' => 'oauth',
      'sign-in' => 'sign in',
      'sso' => 'sso',
    ),
    'donate_link' => 'https://rtcamp.com/',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/login-with-google/assets/icon-128x128.png?rev=2402713',
      '2x' => 'https://ps.w.org/login-with-google/assets/icon-256x256.png?rev=2402713',
    ),
    'wporg' => true,
  ),
  24 => 
  array (
    'name' => 'Search with Google',
    'slug' => 'search-with-google',
    'version' => '1.0',
    'author' => '<a href="https://rtCamp.com">rtCamp</a>',
    'author_profile' => 'https://profiles.wordpress.org/rtcamp',
    'requires' => '4.8',
    'tested' => '5.5.6',
    'requires_php' => '7.0',
    'rating' => 60,
    'ratings' => 
    array (
      1 => 1,
      2 => 0,
      3 => 0,
      4 => 0,
      5 => 1,
    ),
    'num_ratings' => 2,
    'support_threads' => 1,
    'support_threads_resolved' => 0,
    'active_installs' => 20,
    'downloaded' => 308,
    'last_updated' => '2020-10-19 5:28pm GMT',
    'added' => '2020-10-19',
    'homepage' => '',
    'short_description' => 'Replace WordPress default search with server-side rendered Google Custom Search results.',
    'download_link' => 'https://downloads.wordpress.org/plugin/search-with-google.zip',
    'tags' => 
    array (
      'cse' => 'cse',
      'custom-search-engine' => 'custom search engine',
      'google' => 'google',
      'programmable-search' => 'programmable search',
      'search' => 'search',
    ),
    'donate_link' => 'https://rtcamp.com/',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/search-with-google/assets/icon-128x128.png?rev=2402707',
      '2x' => 'https://ps.w.org/search-with-google/assets/icon-256x256.png?rev=2402707',
    ),
    'wporg' => true,
  ),
  25 => 
  array (
    'name' => 'Page Builder Gutenberg Blocks – CoBlocks',
    'slug' => 'coblocks',
    'version' => '2.17.0',
    'author' => '<a href="https://www.godaddy.com">GoDaddy</a>',
    'author_profile' => 'https://profiles.wordpress.org/godaddy',
    'requires' => '5.0',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 88,
    'ratings' => 
    array (
      1 => 7,
      2 => 3,
      3 => 4,
      4 => 5,
      5 => 63,
    ),
    'num_ratings' => 82,
    'support_threads' => 16,
    'support_threads_resolved' => 3,
    'active_installs' => 500000,
    'downloaded' => 5728868,
    'last_updated' => '2021-10-05 4:45pm GMT',
    'added' => '2018-04-19',
    'homepage' => '',
    'short_description' => 'CoBlocks is a suite of page builder WordPress blocks for Gutenberg, with 10+ new blocks and a true page builder experience with rows and columns.',
    'download_link' => 'https://downloads.wordpress.org/plugin/coblocks.2.17.0.zip',
    'tags' => 
    array (
      'blocks' => 'blocks',
      'gutenberg' => 'gutenberg',
      'gutenberg-blocks' => 'gutenberg blocks',
      'page-builder' => 'page builder',
      'wordpress-blocks' => 'wordpress blocks',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/coblocks/assets/icon-128x128.jpg?rev=2243972',
      '2x' => 'https://ps.w.org/coblocks/assets/icon-256x256.jpg?rev=2243972',
    ),
    'wporg' => true,
  ),
  26 => 
  array (
    'name' => 'Simple Author Box',
    'slug' => 'simple-author-box',
    'version' => '2.42',
    'author' => '<a href="https://www.webfactoryltd.com/">WebFactory Ltd</a>',
    'author_profile' => 'https://profiles.wordpress.org/webfactory',
    'requires' => '4.6',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 88,
    'ratings' => 
    array (
      1 => 9,
      2 => 0,
      3 => 5,
      4 => 8,
      5 => 75,
    ),
    'num_ratings' => 97,
    'support_threads' => 5,
    'support_threads_resolved' => 5,
    'active_installs' => 50000,
    'downloaded' => 910141,
    'last_updated' => '2021-08-13 8:08am GMT',
    'added' => '2014-08-08',
    'homepage' => 'https://wpauthorbox.com/',
    'short_description' => 'Add a responsive author box with social icons to any post. Great author box for&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/simple-author-box.2.42.zip',
    'tags' => 
    array (
      'author-bio' => 'author bio',
      'author-box' => 'author box',
      'author-profile-fields' => 'author profile fields',
      'author-social-icons' => 'author social icons',
      'responsive-author-box' => 'responsive author box',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/simple-author-box/assets/icon-128x128.jpg?rev=1821054',
    ),
    'wporg' => true,
  ),
  27 => 
  array (
    'name' => 'Genesis Blocks',
    'slug' => 'genesis-blocks',
    'version' => '1.3.0',
    'author' => '<a href="https://www.studiopress.com/">StudioPress</a>',
    'author_profile' => 'https://profiles.wordpress.org/studiopress',
    'requires' => '5.3',
    'tested' => '5.8.1',
    'requires_php' => '7.1',
    'rating' => 90,
    'ratings' => 
    array (
      1 => 1,
      2 => 0,
      3 => 1,
      4 => 0,
      5 => 10,
    ),
    'num_ratings' => 12,
    'support_threads' => 8,
    'support_threads_resolved' => 1,
    'active_installs' => 40000,
    'downloaded' => 238114,
    'last_updated' => '2021-09-23 6:49pm GMT',
    'added' => '2020-08-25',
    'homepage' => 'https://studiopress.com/genesis-pro/',
    'short_description' => 'A collection of content blocks, sections, &amp; full-page layouts for the block editor.',
    'download_link' => 'https://downloads.wordpress.org/plugin/genesis-blocks.1.3.0.zip',
    'tags' => 
    array (
      'blocks' => 'blocks',
      'editor' => 'editor',
      'gutenberg' => 'gutenberg',
      'gutenberg-blocks' => 'gutenberg blocks',
      'page-builder' => 'page builder',
    ),
    'donate_link' => 'https://studiopress.com',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/genesis-blocks/assets/icon-128x128.png?rev=2368839',
      '2x' => 'https://ps.w.org/genesis-blocks/assets/icon-256x256.png?rev=2368840',
    ),
    'wporg' => true,
  ),
  28 => 
  array (
    'name' => 'MathML Block',
    'slug' => 'mathml-block',
    'version' => '1.2.1',
    'author' => '<a href="http://tunedin.net">adamsilverstein</a>',
    'author_profile' => 'https://profiles.wordpress.org/adamsilverstein',
    'requires' => '5.0',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 90,
    'ratings' => 
    array (
      1 => 0,
      2 => 0,
      3 => 0,
      4 => 1,
      5 => 1,
    ),
    'num_ratings' => 2,
    'support_threads' => 1,
    'support_threads_resolved' => 0,
    'active_installs' => 500,
    'downloaded' => 8180,
    'last_updated' => '2021-09-11 2:30pm GMT',
    'added' => '2018-12-28',
    'homepage' => '',
    'short_description' => 'A MathML block for the WordPress block editor (Gutenberg).',
    'download_link' => 'https://downloads.wordpress.org/plugin/mathml-block.zip',
    'tags' => 
    array (
      'block' => 'block',
      'block-editor' => 'block-editor',
      'gutenberg' => 'gutenberg',
      'math' => 'math',
      'mathml' => 'mathml',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/mathml-block/assets/icon-128x128.png?rev=2002452',
      '2x' => 'https://ps.w.org/mathml-block/assets/icon-256x256.png?rev=2002452',
    ),
    'wporg' => true,
  ),
  29 => 
  array (
    'name' => 'Calculated Fields Form',
    'slug' => 'calculated-fields-form',
    'version' => '1.1.30',
    'author' => '<a href="https://cff.dwbooster.com">CodePeople</a>',
    'author_profile' => 'https://profiles.wordpress.org/codepeople',
    'requires' => '3.0.5',
    'tested' => '5.8.1',
    'requires_php' => false,
    'rating' => 96,
    'ratings' => 
    array (
      1 => 20,
      2 => 2,
      3 => 4,
      4 => 27,
      5 => 686,
    ),
    'num_ratings' => 739,
    'support_threads' => 105,
    'support_threads_resolved' => 105,
    'active_installs' => 60000,
    'downloaded' => 3654737,
    'last_updated' => '2021-10-19 10:31pm GMT',
    'added' => '2013-03-12',
    'homepage' => 'https://cff.dwbooster.com',
    'short_description' => 'Calculated Fields Form allows you to create both simple and rich forms, quickly like a professional. It includes a form builder with dynamic calculate &hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/calculated-fields-form.zip',
    'tags' => 
    array (
      'calculator' => 'calculator',
      'contact-form' => 'contact form',
      'form' => 'form',
      'form-builder' => 'form builder',
      'quote-form' => 'quote form',
    ),
    'donate_link' => 'http://cff.dwbooster.com',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/calculated-fields-form/assets/icon-128x128.jpg?rev=1734377',
      '2x' => 'https://ps.w.org/calculated-fields-form/assets/icon-256x256.jpg?rev=1734377',
    ),
    'wporg' => true,
  ),
  30 => 
  array (
    'name' => 'All in One SEO – Best WordPress SEO Plugin – Easily Improve SEO Rankings &amp; Increase Traffic',
    'slug' => 'all-in-one-seo-pack',
    'version' => '4.1.4.4',
    'author' => '<a href="https://aioseo.com/">All in One SEO Team</a>',
    'author_profile' => 'https://profiles.wordpress.org/smub',
    'requires' => '4.9',
    'tested' => '5.8.1',
    'requires_php' => '5.4',
    'rating' => 92,
    'ratings' => 
    array (
      1 => 166,
      2 => 22,
      3 => 15,
      4 => 60,
      5 => 1570,
    ),
    'num_ratings' => 1833,
    'support_threads' => 132,
    'support_threads_resolved' => 126,
    'active_installs' => 2000000,
    'downloaded' => 86057385,
    'last_updated' => '2021-09-22 3:46pm GMT',
    'added' => '2007-03-30',
    'homepage' => 'https://aioseo.com/',
    'short_description' => 'The original WordPress SEO plugin. Improve your WordPress SEO rankings and traffic with our comprehensive SEO tools and smart SEO optimizations.',
    'download_link' => 'https://downloads.wordpress.org/plugin/all-in-one-seo-pack.4.1.4.4.zip',
    'tags' => 
    array (
      'google-search-console' => 'google search console',
      'meta-description' => 'meta description',
      'schema' => 'schema',
      'seo' => 'seo',
      'xml-sitemap' => 'xml sitemap',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/all-in-one-seo-pack/assets/icon.svg?rev=2443290',
      '2x' => 'https://ps.w.org/all-in-one-seo-pack/assets/icon-256x256.png?rev=2443290',
      'svg' => 'https://ps.w.org/all-in-one-seo-pack/assets/icon.svg?rev=2443290',
    ),
    'wporg' => true,
  ),
  31 => 
  array (
    'name' => 'Weglot Translate &#8211; Translate your WordPress website and go multilingual',
    'slug' => 'weglot',
    'version' => '3.4',
    'author' => '<a href="https://weglot.com/">Weglot Translate team</a>',
    'author_profile' => 'https://profiles.wordpress.org/remyb92',
    'requires' => '4.5',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 96,
    'ratings' => 
    array (
      1 => 40,
      2 => 7,
      3 => 6,
      4 => 27,
      5 => 1225,
    ),
    'num_ratings' => 1305,
    'support_threads' => 5,
    'support_threads_resolved' => 4,
    'active_installs' => 40000,
    'downloaded' => 1241302,
    'last_updated' => '2021-09-24 3:41pm GMT',
    'added' => '2015-09-27',
    'homepage' => 'http://wordpress.org/plugins/weglot/',
    'short_description' => 'Translate your WordPress website in 110+ languages within minutes with Weglot Translate, without any coding.',
    'download_link' => 'https://downloads.wordpress.org/plugin/weglot.3.4.zip',
    'tags' => 
    array (
      'language' => 'language',
      'localization' => 'localization',
      'multilingual' => 'multilingual',
      'translate' => 'translate',
      'translation' => 'translation',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/weglot/assets/icon-128x128.png?rev=2186774',
      '2x' => 'https://ps.w.org/weglot/assets/icon-256x256.png?rev=2186774',
    ),
    'wporg' => true,
  ),
  32 => 
  array (
    'name' => 'Rank Math SEO – Best SEO Plugin For WordPress To Increase Your SEO Traffic',
    'slug' => 'seo-by-rank-math',
    'version' => '1.0.74',
    'author' => '<a href="https://s.rankmath.com/home">Rank Math</a>',
    'author_profile' => 'https://profiles.wordpress.org/rankmath',
    'requires' => '5.6',
    'tested' => '5.8.1',
    'requires_php' => '7.2',
    'rating' => 98,
    'ratings' => 
    array (
      1 => 74,
      2 => 17,
      3 => 21,
      4 => 53,
      5 => 3561,
    ),
    'num_ratings' => 3726,
    'support_threads' => 124,
    'support_threads_resolved' => 120,
    'active_installs' => 1000000,
    'downloaded' => 21556610,
    'last_updated' => '2021-10-13 8:38am GMT',
    'added' => '2018-11-19',
    'homepage' => 'https://s.rankmath.com/home',
    'short_description' => 'Rank Math SEO is the Best WordPress SEO plugin combines the features of many SEO tools in a single package &amp; helps you multiply your SEO traffic.',
    'download_link' => 'https://downloads.wordpress.org/plugin/seo-by-rank-math.1.0.74.zip',
    'tags' => 
    array (
      'google-search-console' => 'google search console',
      'redirection' => 'redirection',
      'schema' => 'schema',
      'seo' => 'seo',
      'sitemap' => 'sitemap',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/seo-by-rank-math/assets/icon.svg?rev=2348086',
      '2x' => 'https://ps.w.org/seo-by-rank-math/assets/icon-256x256.png?rev=2348086',
      'svg' => 'https://ps.w.org/seo-by-rank-math/assets/icon.svg?rev=2348086',
    ),
    'wporg' => true,
  ),
  33 => 
  array (
    'name' => 'Head, Footer and Post Injections',
    'slug' => 'header-footer',
    'version' => '3.2.2',
    'author' => '<a href="https://www.satollo.net">Stefano Lissa</a>',
    'author_profile' => 'https://profiles.wordpress.org/satollo',
    'requires' => '4.0',
    'tested' => '5.7.3',
    'requires_php' => '5.6',
    'rating' => 98,
    'ratings' => 
    array (
      1 => 3,
      2 => 2,
      3 => 4,
      4 => 13,
      5 => 627,
    ),
    'num_ratings' => 649,
    'support_threads' => 1,
    'support_threads_resolved' => 0,
    'active_installs' => 300000,
    'downloaded' => 2808987,
    'last_updated' => '2021-03-17 1:26pm GMT',
    'added' => '2008-04-07',
    'homepage' => 'https://www.satollo.net/plugins/header-footer',
    'short_description' => 'Header and Footer plugin let you to add html code to the head and footer sections of your blog... and more!',
    'download_link' => 'https://downloads.wordpress.org/plugin/header-footer.3.2.2.zip',
    'tags' => 
    array (
      'blog' => 'blog',
      'footer' => 'footer',
      'header' => 'header',
      'page' => 'page',
      'single' => 'single',
    ),
    'donate_link' => 'http://www.satollo.net/donations',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/header-footer/assets/icon-256x256.png?rev=1064219',
      '2x' => 'https://ps.w.org/header-footer/assets/icon-256x256.png?rev=1064219',
    ),
    'wporg' => true,
  ),
  34 => 
  array (
    'name' => 'WP Rocket',
    'slug' => 'wp-rocket',
    'homepage' => 'https://wp-rocket.me/',
    'short_description' => '<p>Powerful caching to speed up your WordPress website in a few clicks. No coding required.</p>
',
    'icons' => 
    array (
      '1x' => 'https://amp-wp.org/wp-content/uploads/2020/06/WP-Rocket-285x160.png',
      '2x' => 'https://amp-wp.org/wp-content/uploads/2020/06/WP-Rocket-372x209.png',
      'svg' => '',
    ),
    'wporg' => false,
  ),
  35 => 
  array (
    'name' => 'Statify',
    'slug' => 'statify',
    'version' => '1.8.3',
    'author' => '<a href="https://pluginkollektiv.org/">pluginkollektiv</a>',
    'author_profile' => 'https://profiles.wordpress.org/pluginkollektiv',
    'requires' => '4.7',
    'tested' => '5.8.1',
    'requires_php' => '5.2',
    'rating' => 94,
    'ratings' => 
    array (
      1 => 2,
      2 => 0,
      3 => 0,
      4 => 3,
      5 => 33,
    ),
    'num_ratings' => 38,
    'support_threads' => 2,
    'support_threads_resolved' => 1,
    'active_installs' => 200000,
    'downloaded' => 1524691,
    'last_updated' => '2021-07-17 8:46am GMT',
    'added' => '2011-03-16',
    'homepage' => 'https://statify.pluginkollektiv.org/',
    'short_description' => 'Visitor statistics for WordPress with focus on data protection, transparency and clarity. Perfect as a widget in your WordPress Dashboard.',
    'download_link' => 'https://downloads.wordpress.org/plugin/statify.1.8.3.zip',
    'tags' => 
    array (
      'analytics' => 'analytics',
      'dashboard' => 'dashboard',
      'pageviews' => 'pageviews',
      'privacy' => 'privacy',
      'statistics' => 'statistics',
    ),
    'donate_link' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=TD4AMD2D8EMZW',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/statify/assets/icon-128x128.png?rev=2355063',
      '2x' => 'https://ps.w.org/statify/assets/icon-256x256.png?rev=2355063',
    ),
    'wporg' => true,
  ),
  36 => 
  array (
    'name' => 'LIQUID BLOCKS GALLERY 37+ Free Designs',
    'slug' => 'liquid-blocks',
    'version' => '1.1.1',
    'author' => '<a href="https://lqd.jp/wp/">LIQUID DESIGN Ltd.</a>',
    'author_profile' => 'https://profiles.wordpress.org/lqd',
    'requires' => '5.2',
    'tested' => '5.8.1',
    'requires_php' => false,
    'rating' => 100,
    'ratings' => 
    array (
      1 => 0,
      2 => 0,
      3 => 0,
      4 => 0,
      5 => 1,
    ),
    'num_ratings' => 1,
    'support_threads' => 1,
    'support_threads_resolved' => 0,
    'active_installs' => 4000,
    'downloaded' => 21085,
    'last_updated' => '2021-07-22 6:55am GMT',
    'added' => '2019-10-18',
    'homepage' => 'https://lqd.jp/wp/plugin.html',
    'short_description' => 'If you’re looking to create block page sections that look great give LIQUID BLOCKS a&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/liquid-blocks.zip',
    'tags' => 
    array (
      'block' => 'block',
      'block-editor' => 'block-editor',
      'blocks' => 'blocks',
      'editor' => 'editor',
      'gutenberg' => 'gutenberg',
    ),
    'donate_link' => 'https://lqd.jp/wp/plugin.html',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/liquid-blocks/assets/icon-128x128.png?rev=2175390',
    ),
    'wporg' => true,
  ),
  37 => 
  array (
    'name' => 'Schema',
    'slug' => 'schema',
    'version' => '1.7.9.3',
    'author' => '<a href="http://zebida.com">Hesham</a>',
    'author_profile' => 'https://profiles.wordpress.org/hishaman',
    'requires' => '4.0',
    'tested' => '5.8.1',
    'requires_php' => '5.4',
    'rating' => 90,
    'ratings' => 
    array (
      1 => 15,
      2 => 6,
      3 => 4,
      4 => 8,
      5 => 163,
    ),
    'num_ratings' => 196,
    'support_threads' => 7,
    'support_threads_resolved' => 1,
    'active_installs' => 60000,
    'downloaded' => 1109761,
    'last_updated' => '2021-10-13 3:10pm GMT',
    'added' => '2016-05-11',
    'homepage' => 'https://schema.press',
    'short_description' => 'Get the next generation of Schema Structured Data to enhance your WordPress site presentation in Google search results.',
    'download_link' => 'https://downloads.wordpress.org/plugin/schema.zip',
    'tags' => 
    array (
      'json-ld' => 'JSON-LD',
      'rich-snippets' => 'rich snippets',
      'schema' => 'schema',
      'schema-org' => 'schema.org',
      'structured-data' => 'structured data',
    ),
    'donate_link' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NGVUBT2QXN7YL',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/schema/assets/icon-128x128.png?rev=1750172',
      '2x' => 'https://ps.w.org/schema/assets/icon-256x256.png?rev=1750173',
    ),
    'wporg' => true,
  ),
  38 => 
  array (
    'name' => 'Iframely &#8211; rich media embeds for 2000+ publishers',
    'slug' => 'iframely',
    'version' => '0.7.2',
    'author' => '<a href="https://iframely.com/?from=wp">Itteco Corp.</a>',
    'author_profile' => 'https://profiles.wordpress.org/ivanp',
    'requires' => '3.5.1',
    'tested' => '5.4.7',
    'requires_php' => false,
    'rating' => 80,
    'ratings' => 
    array (
      1 => 2,
      2 => 0,
      3 => 1,
      4 => 0,
      5 => 7,
    ),
    'num_ratings' => 10,
    'support_threads' => 2,
    'support_threads_resolved' => 1,
    'active_installs' => 3000,
    'downloaded' => 97554,
    'last_updated' => '2020-05-22 5:21pm GMT',
    'added' => '2013-10-03',
    'homepage' => 'http://wordpress.org/plugins/iframely/',
    'short_description' => 'Iframely extends WordPress default rich media embeds and adds support of over 2000 more providers and cards as URL previews for the rest of the Web.',
    'download_link' => 'https://downloads.wordpress.org/plugin/iframely.zip',
    'tags' => 
    array (
      'embed' => 'embed',
      'embed-code' => 'embed code',
      'iframely' => 'iframely',
      'oembed' => 'oembed',
      'responsive' => 'responsive',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      'default' => 'https://s.w.org/plugins/geopattern-icon/iframely.svg',
    ),
    'wporg' => true,
  ),
  39 => 
  array (
    'name' => 'Pym.js Embeds',
    'slug' => 'pym-shortcode',
    'version' => '1.3.2.4',
    'author' => '<a href="https://labs.inn.org/">INN Labs</a>',
    'author_profile' => 'https://profiles.wordpress.org/automattic',
    'requires' => '3.0.1',
    'tested' => '5.4.7',
    'requires_php' => '5.3',
    'rating' => 0,
    'ratings' => 
    array (
      1 => 0,
      2 => 0,
      3 => 0,
      4 => 0,
      5 => 0,
    ),
    'num_ratings' => 0,
    'support_threads' => 1,
    'support_threads_resolved' => 0,
    'active_installs' => 100,
    'downloaded' => 2353,
    'last_updated' => '2020-03-26 6:09pm GMT',
    'added' => '2016-06-17',
    'homepage' => 'https://github.com/INN/pym-shortcode',
    'short_description' => 'A WordPress block and shortcode for embedding iframes that are responsive horizontally and vertically, using&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/pym-shortcode.1.3.2.4.zip',
    'tags' => 
    array (
      'embeds' => 'Embeds',
      'iframe' => 'iframe',
      'javascript' => 'javascript',
      'responsive' => 'responsive',
      'shortcode' => 'shortcode',
    ),
    'donate_link' => 'https://inn.org/donate',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/pym-shortcode/assets/icon.svg?rev=1944461',
      'svg' => 'https://ps.w.org/pym-shortcode/assets/icon.svg?rev=1944461',
    ),
    'wporg' => true,
  ),
  40 => 
  array (
    'name' => 'PWA',
    'slug' => 'pwa',
    'version' => '0.6.0',
    'author' => '<a href="https://github.com/GoogleChromeLabs/pwa-wp/graphs/contributors">PWA Plugin Contributors</a>',
    'author_profile' => 'https://profiles.wordpress.org/westonruter',
    'requires' => '5.5',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 86,
    'ratings' => 
    array (
      1 => 3,
      2 => 0,
      3 => 0,
      4 => 0,
      5 => 13,
    ),
    'num_ratings' => 16,
    'support_threads' => 10,
    'support_threads_resolved' => 6,
    'active_installs' => 40000,
    'downloaded' => 301750,
    'last_updated' => '2021-09-21 7:17pm GMT',
    'added' => '2018-07-12',
    'homepage' => 'https://github.com/GoogleChromeLabs/pwa-wp',
    'short_description' => 'WordPress feature plugin to bring Progressive Web App (PWA) capabilities to Core',
    'download_link' => 'https://downloads.wordpress.org/plugin/pwa.0.6.0.zip',
    'tags' => 
    array (
      'https' => 'https',
      'progressive-web-apps' => 'progressive web apps',
      'pwa' => 'pwa',
      'service-workers' => 'service-workers.',
      'web-app-manifest' => 'web app manifest',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/pwa/assets/icon.svg?rev=1908485',
      '2x' => 'https://ps.w.org/pwa/assets/icon-256x256.png?rev=1908485',
      'svg' => 'https://ps.w.org/pwa/assets/icon.svg?rev=1908485',
    ),
    'wporg' => true,
  ),
  41 => 
  array (
    'name' => 'MC4WP: Mailchimp for WordPress',
    'slug' => 'mailchimp-for-wp',
    'version' => '4.8.6',
    'author' => '<a href="https://ibericode.com/">ibericode</a>',
    'author_profile' => 'https://profiles.wordpress.org/dvankooten',
    'requires' => '4.6',
    'tested' => '5.8.1',
    'requires_php' => '5.3',
    'rating' => 96,
    'ratings' => 
    array (
      1 => 36,
      2 => 10,
      3 => 16,
      4 => 35,
      5 => 1286,
    ),
    'num_ratings' => 1383,
    'support_threads' => 32,
    'support_threads_resolved' => 31,
    'active_installs' => 2000000,
    'downloaded' => 36072428,
    'last_updated' => '2021-08-04 7:14am GMT',
    'added' => '2013-06-19',
    'homepage' => 'https://www.mc4wp.com/#utm_source=wp-plugin&utm_medium=mailchimp-for-wp&utm_campaign=plugins-page',
    'short_description' => 'Mailchimp for WordPress, the #1 unofficial Mailchimp plugin.',
    'download_link' => 'https://downloads.wordpress.org/plugin/mailchimp-for-wp.4.8.6.zip',
    'tags' => 
    array (
      'email' => 'email',
      'mailchimp' => 'mailchimp',
      'marketing' => 'marketing',
      'mc4wp' => 'mc4wp',
      'newsletter' => 'newsletter',
    ),
    'donate_link' => 'https://www.mc4wp.com/#utm_source=wp-plugin-repo&utm_medium=mailchimp-for-wp&utm_campaign=donate-link',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/mailchimp-for-wp/assets/icon-128x128.png?rev=1224577',
      '2x' => 'https://ps.w.org/mailchimp-for-wp/assets/icon-256x256.png?rev=1224577',
    ),
    'wporg' => true,
  ),
  42 => 
  array (
    'name' => 'Site Kit by Google',
    'slug' => 'google-site-kit',
    'homepage' => 'https://sitekit.withgoogle.com/',
    'short_description' => '<p>Site Kit is the official WordPress plugin from Google for insights about how people find and use your site. Site Kit is the one-stop solution to deploy, manage, and get insights from critical Google tools to make the site successful on the web. It provides authoritative, up-to-date insights from multiple Google products directly on the</p>
<p class="is-style-arrow-link"><a class="moretag" href="https://amp-wp.org/ecosystem/google-site-kit/">Read More</a></p>
',
    'icons' => 
    array (
      '1x' => 'https://amp-wp.org/wp-content/uploads/2019/12/site-kit-by-google-logo-285x160.png',
      '2x' => 'https://amp-wp.org/wp-content/uploads/2019/12/site-kit-by-google-logo-372x209.png',
      'svg' => '',
    ),
    'wporg' => false,
  ),
  43 => 
  array (
    'name' => 'Newspack Blocks',
    'slug' => 'newspack-blocks',
    'homepage' => 'https://github.com/Automattic/newspack-blocks',
    'short_description' => '<p>A collection of useful and easy to use Gutenberg based blocks, developed primarily for the Newspack project.</p>
',
    'icons' => 
    array (
      '1x' => 'https://amp-wp.org/wp-content/uploads/2019/11/newspack_blocks-285x160.jpg',
      '2x' => 'https://amp-wp.org/wp-content/uploads/2019/11/newspack_blocks-372x209.jpg',
      'svg' => '',
    ),
    'wporg' => false,
  ),
  44 => 
  array (
    'name' => 'Advanced Ads – Ad Manager &amp; AdSense',
    'slug' => 'advanced-ads',
    'version' => '1.29.1',
    'author' => '<a href="https://wpadvancedads.com">Thomas Maier, Advanced Ads GmbH</a>',
    'author_profile' => 'https://profiles.wordpress.org/webzunft',
    'requires' => '4.9',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 98,
    'ratings' => 
    array (
      1 => 17,
      2 => 1,
      3 => 9,
      4 => 21,
      5 => 1195,
    ),
    'num_ratings' => 1243,
    'support_threads' => 71,
    'support_threads_resolved' => 65,
    'active_installs' => 100000,
    'downloaded' => 5345903,
    'last_updated' => '2021-10-14 10:40am GMT',
    'added' => '2014-06-23',
    'homepage' => 'https://wpadvancedads.com',
    'short_description' => 'Manage and optimize all ad types. Support for Google AdSense Auto ads, Amazon, image banners, HTML, page builder, ad widget, ad rotations, ads.txt',
    'download_link' => 'https://downloads.wordpress.org/plugin/advanced-ads.1.29.1.zip',
    'tags' => 
    array (
      'ad-manager' => 'ad manager',
      'ad-rotation' => 'ad rotation',
      'ads' => 'ads',
      'adsense' => 'adsense',
      'banner' => 'banner',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/advanced-ads/assets/icon-128x128.gif?rev=2293174',
      '2x' => 'https://ps.w.org/advanced-ads/assets/icon-256x256.gif?rev=2293174',
    ),
    'wporg' => true,
  ),
  45 => 
  array (
    'name' => 'Syntax-highlighting Code Block (with Server-side Rendering)',
    'slug' => 'syntax-highlighting-code-block',
    'version' => '1.3.1',
    'author' => '<a href="https://weston.ruter.net/">Weston Ruter</a>',
    'author_profile' => 'https://profiles.wordpress.org/westonruter',
    'requires' => '5.5',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 100,
    'ratings' => 
    array (
      1 => 0,
      2 => 0,
      3 => 0,
      4 => 0,
      5 => 18,
    ),
    'num_ratings' => 18,
    'support_threads' => 3,
    'support_threads_resolved' => 2,
    'active_installs' => 1000,
    'downloaded' => 12485,
    'last_updated' => '2021-09-21 7:11pm GMT',
    'added' => '2019-07-30',
    'homepage' => 'https://github.com/westonruter/syntax-highlighting-code-block',
    'short_description' => 'Extending the Code block with syntax highlighting rendered on the server, thus being AMP-compatible and&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/syntax-highlighting-code-block.1.3.1.zip',
    'tags' => 
    array (
      'block' => 'block',
      'code' => 'code',
      'code-highlighting' => 'code highlighting',
      'code-syntax' => 'code syntax',
      'syntax-highlight' => 'syntax highlight',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/syntax-highlighting-code-block/assets/icon.svg?rev=2131108',
      '2x' => 'https://ps.w.org/syntax-highlighting-code-block/assets/icon-256x256.png?rev=2131108',
      'svg' => 'https://ps.w.org/syntax-highlighting-code-block/assets/icon.svg?rev=2131108',
    ),
    'wporg' => true,
  ),
  46 => 
  array (
    'name' => 'Contact Form by WPForms &#8211; Drag &amp; Drop Form Builder for WordPress',
    'slug' => 'wpforms-lite',
    'version' => '1.7.0',
    'author' => '<a href="https://wpforms.com">WPForms</a>',
    'author_profile' => 'https://profiles.wordpress.org/jaredatch',
    'requires' => '4.9',
    'tested' => '5.8.1',
    'requires_php' => '5.5',
    'rating' => 98,
    'ratings' => 
    array (
      1 => 218,
      2 => 47,
      3 => 57,
      4 => 226,
      5 => 9825,
    ),
    'num_ratings' => 10373,
    'support_threads' => 87,
    'support_threads_resolved' => 74,
    'active_installs' => 5000000,
    'downloaded' => 84759844,
    'last_updated' => '2021-10-07 11:02am GMT',
    'added' => '2016-03-14',
    'homepage' => 'https://wpforms.com',
    'short_description' => 'The best WordPress contact form plugin. Drag &amp; Drop online form builder that helps you create beautiful contact forms with just a few clicks.',
    'download_link' => 'https://downloads.wordpress.org/plugin/wpforms-lite.1.7.0.zip',
    'tags' => 
    array (
      'contact-form' => 'contact form',
      'contact-form-plugin' => 'contact form plugin',
      'custom-form' => 'custom form',
      'form-builder' => 'form builder',
      'forms' => 'forms',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/wpforms-lite/assets/icon.svg?rev=2574198',
      '2x' => 'https://ps.w.org/wpforms-lite/assets/icon-256x256.png?rev=2574201',
      'svg' => 'https://ps.w.org/wpforms-lite/assets/icon.svg?rev=2574198',
    ),
    'wporg' => true,
  ),
  47 => 
  array (
    'name' => 'MonsterInsights &#8211; Google Analytics Dashboard for WordPress (Website Stats Made Easy)',
    'slug' => 'google-analytics-for-wordpress',
    'version' => '8.1.0',
    'author' => '<a href="https://www.monsterinsights.com/?utm_source=liteplugin&utm_medium=pluginheader&utm_campaign=authoruri&utm_content=7%2E0%2E0">MonsterInsights</a>',
    'author_profile' => 'https://profiles.wordpress.org/chriscct7',
    'requires' => '4.8.0',
    'tested' => '5.8.1',
    'requires_php' => '5.5',
    'rating' => 92,
    'ratings' => 
    array (
      1 => 194,
      2 => 39,
      3 => 35,
      4 => 77,
      5 => 2104,
    ),
    'num_ratings' => 2449,
    'support_threads' => 11,
    'support_threads_resolved' => 9,
    'active_installs' => 3000000,
    'downloaded' => 101841550,
    'last_updated' => '2021-09-30 7:56am GMT',
    'added' => '2007-09-14',
    'homepage' => 'https://www.monsterinsights.com/?utm_source=liteplugin&utm_medium=pluginheader&utm_campaign=pluginurl&utm_content=7%2E0%2E0',
    'short_description' => 'The best free Google Analytics plugin for WordPress. See how visitors find and use your website, so you can grow your business.',
    'download_link' => 'https://downloads.wordpress.org/plugin/google-analytics-for-wordpress.8.1.0.zip',
    'tags' => 
    array (
      'google-analytics' => 'google analytics',
      'google-analytics-dashboard' => 'google analytics dashboard',
      'google-analytics-widget' => 'google analytics widget',
      'woocommerce-stats' => 'WooCommerce stats',
      'wordpress-analytics' => 'WordPress analytics',
    ),
    'donate_link' => 'http://www.wpbeginner.com/wpbeginner-needs-your-help/',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/google-analytics-for-wordpress/assets/icon.svg?rev=1598927',
      '2x' => 'https://ps.w.org/google-analytics-for-wordpress/assets/icon-256x256.png?rev=1598927',
      'svg' => 'https://ps.w.org/google-analytics-for-wordpress/assets/icon.svg?rev=1598927',
    ),
    'wporg' => true,
  ),
  48 => 
  array (
    'name' => 'Atomic Blocks &#8211; Gutenberg Blocks Collection',
    'slug' => 'atomic-blocks',
    'version' => '2.9.0',
    'author' => '<a href="http://atomicblocks.com">atomicblocks</a>',
    'author_profile' => 'https://profiles.wordpress.org/atomicblocks',
    'requires' => '5.3',
    'tested' => '5.5.6',
    'requires_php' => '5.6',
    'rating' => 86,
    'ratings' => 
    array (
      1 => 5,
      2 => 0,
      3 => 1,
      4 => 6,
      5 => 31,
    ),
    'num_ratings' => 43,
    'support_threads' => 1,
    'support_threads_resolved' => 0,
    'active_installs' => 40000,
    'downloaded' => 999721,
    'last_updated' => '2020-10-28 4:53pm GMT',
    'added' => '2018-03-26',
    'homepage' => 'https://atomicblocks.com',
    'short_description' => 'A collection of beautiful, customizable Gutenberg blocks for the new block editor.',
    'download_link' => 'https://downloads.wordpress.org/plugin/atomic-blocks.2.9.0.zip',
    'tags' => 
    array (
      'blocks' => 'blocks',
      'editor' => 'editor',
      'gutenberg' => 'gutenberg',
      'gutenberg-blocks' => 'gutenberg blocks',
      'page-builder' => 'page builder',
    ),
    'donate_link' => 'https://atomicblocks.com',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/atomic-blocks/assets/icon-128x128.jpg?rev=1914920',
      '2x' => 'https://ps.w.org/atomic-blocks/assets/icon-256x256.jpg?rev=1914921',
    ),
    'wporg' => true,
  ),
  49 => 
  array (
    'name' => 'Akismet Spam Protection',
    'slug' => 'akismet',
    'version' => '4.2.1',
    'author' => '<a href="https://automattic.com/wordpress-plugins/">Automattic</a>',
    'author_profile' => 'https://profiles.wordpress.org/automattic',
    'requires' => '5.0',
    'tested' => '5.8.1',
    'requires_php' => false,
    'rating' => 94,
    'ratings' => 
    array (
      1 => 40,
      2 => 10,
      3 => 13,
      4 => 45,
      5 => 815,
    ),
    'num_ratings' => 923,
    'support_threads' => 12,
    'support_threads_resolved' => 8,
    'active_installs' => 5000000,
    'downloaded' => 221318879,
    'last_updated' => '2021-10-01 6:28pm GMT',
    'added' => '2005-10-20',
    'homepage' => 'https://akismet.com/',
    'short_description' => 'The best anti-spam protection to block spam comments and spam in a contact form. The most trusted antispam solution for WordPress and WooCommerce.',
    'download_link' => 'https://downloads.wordpress.org/plugin/akismet.4.2.1.zip',
    'tags' => 
    array (
      'anti-spam' => 'anti-spam',
      'antispam' => 'antispam',
      'comments' => 'comments',
      'contact-form' => 'contact form',
      'spam' => 'spam',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/akismet/assets/icon-128x128.png?rev=969272',
      '2x' => 'https://ps.w.org/akismet/assets/icon-256x256.png?rev=969272',
    ),
    'wporg' => true,
  ),
  50 => 
  array (
    'name' => 'WP GDPR Cookie Notice',
    'slug' => 'wp-gdpr-cookie-notice',
    'version' => '1.0.0-rc.1',
    'author' => '<a href="https://felix-arntz.me">Felix Arntz</a>',
    'author_profile' => 'https://profiles.wordpress.org/flixos90',
    'requires' => '4.9.6',
    'tested' => '5.7.3',
    'requires_php' => '7.0',
    'rating' => 76,
    'ratings' => 
    array (
      1 => 4,
      2 => 0,
      3 => 0,
      4 => 0,
      5 => 9,
    ),
    'num_ratings' => 13,
    'support_threads' => 1,
    'support_threads_resolved' => 0,
    'active_installs' => 700,
    'downloaded' => 6164,
    'last_updated' => '2021-04-02 11:51pm GMT',
    'added' => '2019-03-01',
    'homepage' => 'https://wordpress.org/plugins/wp-gdpr-cookie-notice/',
    'short_description' => 'Simple performant cookie consent notice that supports AMP, Web Stories, granular cookie control and live&hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/wp-gdpr-cookie-notice.1.0.0-rc.1.zip',
    'tags' => 
    array (
      'amp' => 'amp',
      'cookie-consent' => 'cookie consent',
      'cookie-notice' => 'cookie notice',
      'gdpr' => 'GDPR',
      'web-stories' => 'web stories',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/wp-gdpr-cookie-notice/assets/icon-128x128.png?rev=2042024',
      '2x' => 'https://ps.w.org/wp-gdpr-cookie-notice/assets/icon-256x256.png?rev=2042024',
    ),
    'wporg' => true,
  ),
  51 => 
  array (
    'name' => 'WordPress Share Buttons Plugin – AddThis',
    'slug' => 'addthis',
    'version' => '6.2.6',
    'author' => '<a href="http://www.addthis.com">The AddThis Team</a>',
    'author_profile' => 'https://profiles.wordpress.org/arnavarro',
    'requires' => '3.0',
    'tested' => '5.2.12',
    'requires_php' => false,
    'rating' => 84,
    'ratings' => 
    array (
      1 => 75,
      2 => 25,
      3 => 22,
      4 => 46,
      5 => 444,
    ),
    'num_ratings' => 612,
    'support_threads' => 1,
    'support_threads_resolved' => 0,
    'active_installs' => 100000,
    'downloaded' => 5077821,
    'last_updated' => '2019-07-10 5:19pm GMT',
    'added' => '2008-12-23',
    'homepage' => 'https://wordpress.org/plugins/addthis/',
    'short_description' => 'Now compatible with the AMP Plugin! Free Share Buttons from AddThis. Share to Messenger, WhatsApp, Facebook, Twitter, Pinterest and many more.',
    'download_link' => 'https://downloads.wordpress.org/plugin/addthis.6.2.6.zip',
    'tags' => 
    array (
      'share-buttons' => 'share buttons',
      'social' => 'social',
      'social-marketing' => 'Social Marketing',
      'social-share' => 'social share',
      'social-sharing' => 'social sharing',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/addthis/assets/icon-128x128.png?rev=1223867',
      '2x' => 'https://ps.w.org/addthis/assets/icon-256x256.png?rev=1223867',
    ),
    'wporg' => true,
  ),
  52 => 
  array (
    'name' => 'BigCommerce For WordPress',
    'slug' => 'bigcommerce',
    'version' => '4.18.0',
    'author' => '<a href="https://www.bigcommerce.com/wordpress">BigCommerce</a>',
    'author_profile' => 'https://profiles.wordpress.org/bigcommerce',
    'requires' => '5.2',
    'tested' => '5.8.1',
    'requires_php' => '7.4.0',
    'rating' => 80,
    'ratings' => 
    array (
      1 => 8,
      2 => 1,
      3 => 0,
      4 => 3,
      5 => 27,
    ),
    'num_ratings' => 39,
    'support_threads' => 8,
    'support_threads_resolved' => 0,
    'active_installs' => 1000,
    'downloaded' => 60763,
    'last_updated' => '2021-10-07 1:18am GMT',
    'added' => '2018-11-16',
    'homepage' => '',
    'short_description' => 'Scale your ecommerce business with WordPress on the front-end and BigCommerce on the back end. Free up server resources from things like catalog manag &hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/bigcommerce.4.18.0.zip',
    'tags' => 
    array (
      'ecommerce' => 'ecommerce',
      'online-store' => 'online store',
      'retail' => 'retail',
      'sell-online' => 'sell online',
      'storefront' => 'storefront',
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/bigcommerce/assets/icon-256x256.png?rev=2141502',
      '2x' => 'https://ps.w.org/bigcommerce/assets/icon-256x256.png?rev=2141502',
    ),
    'wporg' => true,
  ),
  53 => 
  array (
    'name' => 'Yoast SEO',
    'slug' => 'wordpress-seo',
    'version' => '17.4',
    'author' => '<a href="https://yoa.st/1uk">Team Yoast</a>',
    'author_profile' => 'https://profiles.wordpress.org/joostdevalk',
    'requires' => '5.6',
    'tested' => '5.8.1',
    'requires_php' => '5.6.20',
    'rating' => 96,
    'ratings' => 
    array (
      1 => 722,
      2 => 125,
      3 => 175,
      4 => 619,
      5 => 25761,
    ),
    'num_ratings' => 27402,
    'support_threads' => 494,
    'support_threads_resolved' => 442,
    'active_installs' => 5000000,
    'downloaded' => 367035742,
    'last_updated' => '2021-10-19 6:48am GMT',
    'added' => '2010-10-11',
    'homepage' => 'https://yoa.st/1uj',
    'short_description' => 'Improve your WordPress SEO: Write better content and have a fully optimized WordPress site using the Yoast SEO plugin.',
    'download_link' => 'https://downloads.wordpress.org/plugin/wordpress-seo.17.4.zip',
    'tags' => 
    array (
      'content-analysis' => 'Content analysis',
      'readability' => 'Readability',
      'schema' => 'schema',
      'seo' => 'seo',
      'xml-sitemap' => 'xml sitemap',
    ),
    'donate_link' => 'https://yoa.st/1up',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/wordpress-seo/assets/icon.svg?rev=2363699',
      '2x' => 'https://ps.w.org/wordpress-seo/assets/icon-256x256.png?rev=2363699',
      'svg' => 'https://ps.w.org/wordpress-seo/assets/icon.svg?rev=2363699',
    ),
    'wporg' => true,
  ),
  54 => 
  array (
    'name' => 'Gutenberg',
    'slug' => 'gutenberg',
    'version' => '11.7.0',
    'author' => 'Gutenberg Team',
    'author_profile' => 'https://profiles.wordpress.org/matveb',
    'requires' => '5.7',
    'tested' => '5.8.1',
    'requires_php' => '5.6',
    'rating' => 42,
    'ratings' => 
    array (
      1 => 2282,
      2 => 202,
      3 => 128,
      4 => 134,
      5 => 710,
    ),
    'num_ratings' => 3456,
    'support_threads' => 60,
    'support_threads_resolved' => 26,
    'active_installs' => 300000,
    'downloaded' => 25104297,
    'last_updated' => '2021-10-13 3:50pm GMT',
    'added' => '2017-06-16',
    'homepage' => 'https://github.com/WordPress/gutenberg',
    'short_description' => 'The Gutenberg plugin provides editing, customization, and site building features to WordPress. This beta plugin allows you to test bleeding-edge featu &hellip;',
    'download_link' => 'https://downloads.wordpress.org/plugin/gutenberg.11.7.0.zip',
    'tags' => 
    array (
    ),
    'donate_link' => '',
    'icons' => 
    array (
      '1x' => 'https://ps.w.org/gutenberg/assets/icon-128x128.jpg?rev=1776042',
      '2x' => 'https://ps.w.org/gutenberg/assets/icon-256x256.jpg?rev=1776042',
    ),
    'wporg' => true,
  ),
  55 => 
  array (
    'name' => 'Setka Editor',
    'slug' => 'setka-editor',
    'homepage' => 'https://setka.io/',
    'short_description' => '<p>Setka Editor is the first WYSIWYG plugin with page builder functionality.</p>
',
    'icons' => 
    array (
      '1x' => 'https://amp-wp.org/wp-content/uploads/2018/11/Setka-Banner-285x160.jpg',
      '2x' => 'https://amp-wp.org/wp-content/uploads/2018/11/Setka-Banner-372x209.jpg',
      'svg' => '',
    ),
    'wporg' => false,
  ),
);