<?php
/**
 * Generated by wp_amp_build.py - do not edit.
 * 
 * This is a list of HTML tags and attributes that are allowed by the
 * AMP specification. Note that the tags have been converted to lowercase.
 *
 * Note: "$REFERENCE_POINT" is a special tag_name value.
 * Reference points are partial tag specs which don't have a defined
 * tag_name.
 */

$spec_file_revision = 320;
$minimum_validator_revision_required = 189;

$allowedtags = array(
	'!doctype' => array(
		'html' => true,
	),
	'$reference_point' => array(
		'update' => true,
		'items' => true,
		'pagination' => true,
		'id' => true,
		'data-sort-time' => true,
		'data-update-time' => true,
		'data-tombstone' => true,
	),
	'a' => array(
		'href' => true,
		'hreflang' => true,
		'rel' => true,
		'role' => true,
		'tabindex' => true,
		'target' => true,
		'download' => true,
		'media' => true,
		'type' => true,
		'border' => true,
		'name' => true,
	),
	'abbr' => array(
	),
	'acronym' => array(
	),
	'address' => array(
	),
	'amp-accordion' => array(
		'disable-session-states' => true,
	),
	'amp-ad' => array(
		'alt' => true,
		'json' => true,
		'src' => true,
		'type' => true,
	),
	'amp-analytics' => array(
		'type' => true,
		'config' => true,
	),
	'amp-anim' => array(
		'alt' => true,
		'attribution' => true,
		'autoplay' => true,
		'controls' => true,
	),
	'amp-apester-media' => array(
		'data-apester-media-id' => true,
		'data-apester-channel-token' => true,
	),
	'amp-app-banner' => array(
		'id' => true,
	),
	'amp-audio' => array(
		'autoplay' => true,
	),
	'amp-auto-ads' => array(
		'type' => true,
	),
	'amp-brid-player' => array(
		'data-partner' => true,
		'data-player' => true,
		'data-playlist' => true,
		'data-video' => true,
	),
	'amp-brightcove' => array(
		'data-account' => true,
		'data-embed' => true,
		'data-player' => true,
		'data-playlist-id' => true,
		'data-video-id' => true,
	),
	'amp-carousel' => array(
		'arrows' => true,
		'autoplay' => true,
		'controls' => true,
		'delay' => true,
		'dots' => true,
		'loop' => true,
		'type' => true,
	),
	'amp-dailymotion' => array(
		'data-endscreen-enable' => true,
		'data-info' => true,
		'data-mute' => true,
		'data-sharing-enable' => true,
		'data-start' => true,
		'data-ui-highlight' => true,
		'data-ui-logo' => true,
		'data-videoid' => true,
	),
	'amp-embed' => array(
		'alt' => true,
		'json' => true,
		'src' => true,
		'type' => true,
	),
	'amp-experiment' => array(
	),
	'amp-facebook' => array(
		'data-href' => true,
	),
	'amp-fit-text' => array(
		'max-font-size' => true,
		'min-font-size' => true,
	),
	'amp-font' => array(
		'font-family' => true,
		'font-style' => true,
		'font-variant' => true,
		'timeout' => true,
		'font-weight' => true,
		'on-error-add-class' => true,
		'on-error-remove-class' => true,
		'on-load-add-class' => true,
		'on-load-remove-class' => true,
	),
	'amp-fx-flying-carpet' => array(
		'height' => true,
	),
	'amp-gfycat' => array(
		'data-gfyid' => true,
		'noautoplay' => true,
	),
	'amp-hulu' => array(
		'data-eid' => true,
	),
	'amp-iframe' => array(
		'allowfullscreen' => true,
		'allowtransparency' => true,
		'frameborder' => true,
		'referrerpolicy' => true,
		'resizable' => true,
		'sandbox' => true,
		'scrolling' => true,
		'src' => true,
		'srcdoc' => true,
	),
	'amp-image-lightbox' => array(
		'controls' => true,
	),
	'amp-img' => array(
		'alt' => true,
		'attribution' => true,
		'placeholder' => true,
	),
	'amp-instagram' => array(
		'alt' => true,
		'data-shortcode' => true,
	),
	'amp-install-serviceworker' => array(
		'src' => true,
	),
	'amp-jwplayer' => array(
		'data-media-id' => true,
		'data-player-id' => true,
		'data-playlist-id' => true,
	),
	'amp-kaltura-player' => array(
		'data-partner' => true,
	),
	'amp-lightbox' => array(
		'controls' => true,
		'from' => true,
		'scrollable' => true,
	),
	'amp-list' => array(
		'credentials' => true,
		'src' => true,
		'template' => true,
	),
	'amp-live-list' => array(
		'id' => true,
		'data-poll-interval' => true,
		'data-max-items-per-page' => true,
		'disabled' => true,
	),
	'amp-o2-player' => array(
		'data-pid' => true,
		'data-bcid' => true,
		'data-bid' => true,
		'data-vid' => true,
	),
	'amp-pinterest' => array(
		'data-do' => true,
	),
	'amp-pixel' => array(
		'src' => true,
	),
	'amp-reach-player' => array(
		'data-embed-id' => true,
	),
	'amp-reddit' => array(
		'data-embedlive' => true,
		'data-embedparent' => true,
		'data-embedtype' => true,
		'data-src' => true,
	),
	'amp-sidebar' => array(
		'side' => true,
	),
	'amp-social-share' => array(
		'type' => true,
		'data-share-endpoint' => true,
	),
	'amp-soundcloud' => array(
		'data-color' => true,
		'data-secret-token' => true,
		'data-trackid' => true,
		'data-visual' => true,
	),
	'amp-springboard-player' => array(
		'data-content-id' => true,
		'data-domain' => true,
		'data-items' => true,
		'data-mode' => true,
		'data-player-id' => true,
		'data-site-id' => true,
	),
	'amp-sticky-ad' => array(
	),
	'amp-twitter' => array(
		'data-tweetid' => true,
	),
	'amp-user-notification' => array(
		'data-show-if-href' => true,
		'data-dismiss-href' => true,
	),
	'amp-video' => array(
		'alt' => true,
		'attribution' => true,
		'autoplay' => true,
		'controls' => true,
		'loop' => true,
		'muted' => true,
		'placeholder' => true,
		'poster' => true,
		'preload' => true,
		'src' => true,
	),
	'amp-vimeo' => array(
		'data-videoid' => true,
	),
	'amp-vine' => array(
		'data-vineid' => true,
	),
	'amp-youtube' => array(
		'autoplay' => true,
		'data-videoid' => true,
	),
	'article' => array(
	),
	'aside' => array(
	),
	'audio' => array(
		'autoplay' => true,
		'controls' => true,
		'loop' => true,
		'muted' => true,
		'preload' => true,
		'src' => true,
	),
	'b' => array(
	),
	'base' => array(
		'href' => true,
		'target' => true,
	),
	'bdi' => array(
	),
	'bdo' => array(
		'dir' => true,
	),
	'big' => array(
	),
	'blockquote' => array(
		'align' => true,
	),
	'body' => array(
	),
	'br' => array(
	),
	'button' => array(
		'disabled' => true,
		'name' => true,
		'role' => true,
		'tabindex' => true,
		'type' => true,
		'value' => true,
		'open-button' => true,
	),
	'caption' => array(
	),
	'center' => array(
	),
	'circle' => array(
		'class' => true,
		'cx' => true,
		'cy' => true,
		'externalresourcesrequired' => true,
		'r' => true,
		'sketch:type' => true,
		'transform' => true,
	),
	'cite' => array(
	),
	'clippath' => array(
		'class' => true,
		'clippathunits' => true,
		'externalresourcesrequired' => true,
		'transform' => true,
	),
	'code' => array(
	),
	'col' => array(
		'span' => true,
	),
	'colgroup' => array(
		'span' => true,
	),
	'data' => array(
	),
	'datalist' => array(
	),
	'dd' => array(
	),
	'defs' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'transform' => true,
	),
	'del' => array(
		'datetime' => true,
	),
	'desc' => array(
		'class' => true,
	),
	'dfn' => array(
	),
	'dir' => array(
	),
	'div' => array(
		'align' => true,
		'submit-success' => true,
		'submit-error' => true,
	),
	'dl' => array(
	),
	'dt' => array(
	),
	'ellipse' => array(
		'class' => true,
		'cx' => true,
		'cy' => true,
		'externalresourcesrequired' => true,
		'rx' => true,
		'ry' => true,
		'sketch:type' => true,
		'transform' => true,
	),
	'em' => array(
	),
	'fieldset' => array(
		'disabled' => true,
		'name' => true,
	),
	'figcaption' => array(
	),
	'figure' => array(
	),
	'filter' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'filterres' => true,
		'filterunits' => true,
		'height' => true,
		'primitiveunits' => true,
		'width' => true,
		'x' => true,
		'y' => true,
	),
	'footer' => array(
	),
	'foreignobject' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'height' => true,
		'transform' => true,
		'width' => true,
		'x' => true,
		'y' => true,
	),
	'form' => array(
		'accept' => true,
		'accept-charset' => true,
		'action' => true,
		'action-xhr' => true,
		'autocomplete' => true,
		'custom-validation-reporting' => true,
		'enctype' => true,
		'method' => true,
		'name' => true,
		'novalidate' => true,
		'target' => true,
	),
	'g' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'transform' => true,
	),
	'glyph' => array(
		'arabic-form' => true,
		'class' => true,
		'd' => true,
		'glyph-name' => true,
		'horiz-adv-x' => true,
		'orientation' => true,
		'unicode' => true,
		'vert-origin-x' => true,
		'vert-origin-y' => true,
		'vert-adv-y' => true,
	),
	'glyphref' => array(
		'class' => true,
		'dx' => true,
		'dy' => true,
		'format' => true,
		'glyphref' => true,
		'x' => true,
		'y' => true,
	),
	'h1' => array(
		'align' => true,
	),
	'h2' => array(
		'align' => true,
	),
	'h3' => array(
		'align' => true,
	),
	'h4' => array(
		'align' => true,
	),
	'h5' => array(
		'align' => true,
	),
	'h6' => array(
		'align' => true,
	),
	'head' => array(
	),
	'header' => array(
	),
	'hgroup' => array(
	),
	'hkern' => array(
		'g1' => true,
		'g2' => true,
		'k' => true,
		'u1' => true,
		'u2' => true,
	),
	'hr' => array(
	),
	'html' => array(
		'\u26a1' => true,
		'\u26a14ads' => true,
	),
	'i' => array(
	),
	'image' => array(
		'externalresourcesrequired' => true,
		'class' => true,
		'height' => true,
		'preserveaspectratio' => true,
		'transform' => true,
		'width' => true,
		'x' => true,
		'y' => true,
		'xlink:actuate' => true,
		'xlink:arcrole' => true,
		'xlink:href' => true,
		'xlink:role' => true,
		'xlink:show' => true,
		'xlink:title' => true,
		'xlink:type' => true,
	),
	'img' => array(
		'alt' => true,
		'ismap' => true,
		'longdesc' => true,
		'src' => true,
		'border' => true,
		'height' => true,
		'width' => true,
	),
	'input' => array(
		'accept' => true,
		'accesskey' => true,
		'autocomplete' => true,
		'autofocus' => true,
		'checked' => true,
		'default-value' => true,
		'disabled' => true,
		'height' => true,
		'inputmode' => true,
		'list' => true,
		'max' => true,
		'maxlength' => true,
		'min' => true,
		'minlength' => true,
		'multiple' => true,
		'name' => true,
		'pattern' => true,
		'placeholder' => true,
		'readonly' => true,
		'required' => true,
		'selectiondirection' => true,
		'size' => true,
		'spellcheck' => true,
		'step' => true,
		'tabindex' => true,
		'type' => true,
		'value' => true,
		'width' => true,
	),
	'ins' => array(
		'datetime' => true,
	),
	'kbd' => array(
	),
	'label' => array(
		'for' => true,
	),
	'legend' => array(
	),
	'li' => array(
		'value' => true,
	),
	'line' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'sketch:type' => true,
		'transform' => true,
		'x1' => true,
		'x2' => true,
		'y1' => true,
		'y2' => true,
	),
	'lineargradient' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'gradientunits' => true,
		'gradienttransform' => true,
		'spreadmethod' => true,
		'x1' => true,
		'y1' => true,
		'x2' => true,
		'y2' => true,
	),
	'link' => array(
		'href' => true,
		'rel' => true,
		'sizes' => true,
		'type' => true,
		'media' => true,
		'itemprop' => true,
	),
	'listing' => array(
	),
	'main' => array(
	),
	'mark' => array(
	),
	'marker' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'markerunits' => true,
		'markerwidth' => true,
		'markerheight' => true,
		'orient' => true,
		'preserveaspectratio' => true,
		'refx' => true,
		'refy' => true,
		'transform' => true,
		'viewbox' => true,
	),
	'mask' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'height' => true,
		'maskcontentunits' => true,
		'maskunits' => true,
		'width' => true,
		'x' => true,
		'y' => true,
	),
	'meta' => array(
		'charset' => true,
		'content' => true,
		'name' => true,
		'http-equiv' => true,
		'property' => true,
		'itemprop' => true,
	),
	'multicol' => array(
	),
	'nav' => array(
	),
	'nextid' => array(
	),
	'nobr' => array(
	),
	'noscript' => array(
	),
	'o:p' => array(
	),
	'ol' => array(
		'reversed' => true,
		'start' => true,
		'type' => true,
	),
	'optgroup' => array(
		'disabled' => true,
		'label' => true,
	),
	'option' => array(
		'disabled' => true,
		'label' => true,
		'selected' => true,
		'value' => true,
	),
	'p' => array(
		'align' => true,
	),
	'path' => array(
		'class' => true,
		'd' => true,
		'externalresourcesrequired' => true,
		'pathlength' => true,
		'sketch:type' => true,
		'transform' => true,
	),
	'pattern' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'height' => true,
		'patternunits' => true,
		'patterncontentunits' => true,
		'patterntransform' => true,
		'preserveaspectratio' => true,
		'viewbox' => true,
		'width' => true,
		'x' => true,
		'y' => true,
	),
	'polygon' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'points' => true,
		'sketch:type' => true,
		'transform' => true,
	),
	'polyline' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'points' => true,
		'sketch:type' => true,
		'transform' => true,
	),
	'pre' => array(
	),
	'q' => array(
	),
	'radialgradient' => array(
		'class' => true,
		'cx' => true,
		'cy' => true,
		'externalresourcesrequired' => true,
		'fx' => true,
		'fy' => true,
		'gradientunits' => true,
		'gradienttransform' => true,
		'r' => true,
		'spreadmethod' => true,
	),
	'rb' => array(
	),
	'rect' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'height' => true,
		'rx' => true,
		'ry' => true,
		'sketch:type' => true,
		'transform' => true,
		'width' => true,
		'x' => true,
		'y' => true,
	),
	'rp' => array(
	),
	'rt' => array(
	),
	'rtc' => array(
	),
	'ruby' => array(
	),
	's' => array(
	),
	'samp' => array(
	),
	'script' => array(
		'async' => true,
		'src' => true,
		'type' => true,
		'custom-element' => true,
		'id' => true,
		'amp-ad-metadata' => true,
		'custom-template' => true,
	),
	'section' => array(
		'expanded' => true,
	),
	'select' => array(
		'autofocus' => true,
		'disabled' => true,
		'multiple' => true,
		'name' => true,
		'required' => true,
		'size' => true,
	),
	'small' => array(
	),
	'source' => array(
		'src' => true,
		'media' => true,
		'type' => true,
	),
	'spacer' => array(
	),
	'span' => array(
	),
	'stop' => array(
		'offset' => true,
		'stop-color' => true,
		'stop-opacity' => true,
	),
	'strike' => array(
	),
	'strong' => array(
	),
	'style' => array(
		'amp-custom' => true,
		'type' => true,
		'amp-boilerplate' => true,
		'amp4ads-boilerplate' => true,
	),
	'sub' => array(
	),
	'sup' => array(
	),
	'svg' => array(
		'class' => true,
		'contentscripttype' => true,
		'contentstyletype' => true,
		'externalresourcesrequired' => true,
		'height' => true,
		'preserveaspectratio' => true,
		'version' => true,
		'viewbox' => true,
		'width' => true,
		'x' => true,
		'y' => true,
		'zoomandpan' => true,
	),
	'symbol' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'preserveaspectratio' => true,
		'viewbox' => true,
	),
	'table' => array(
		'sortable' => true,
		'align' => true,
		'border' => true,
		'bgcolor' => true,
		'cellpadding' => true,
		'cellspacing' => true,
		'width' => true,
	),
	'tbody' => array(
	),
	'td' => array(
		'colspan' => true,
		'headers' => true,
		'rowspan' => true,
		'align' => true,
		'bgcolor' => true,
		'height' => true,
		'valign' => true,
		'width' => true,
	),
	'template' => array(
		'type' => true,
	),
	'text' => array(
		'class' => true,
		'dx' => true,
		'dy' => true,
		'externalresourcesrequired' => true,
		'lengthadjust' => true,
		'rotate' => true,
		'text-anchor' => true,
		'textlength' => true,
		'transform' => true,
		'x' => true,
		'y' => true,
	),
	'textarea' => array(
		'autocomplete' => true,
		'autofocus' => true,
		'cols' => true,
		'disabled' => true,
		'maxlength' => true,
		'minlength' => true,
		'name' => true,
		'placeholder' => true,
		'readonly' => true,
		'required' => true,
		'rows' => true,
		'selectiondirection' => true,
		'selectionend' => true,
		'selectionstart' => true,
		'spellcheck' => true,
		'wrap' => true,
	),
	'textpath' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'method' => true,
		'spacing' => true,
		'startoffset' => true,
	),
	'tfoot' => array(
	),
	'th' => array(
		'abbr' => true,
		'colspan' => true,
		'headers' => true,
		'rowspan' => true,
		'scope' => true,
		'sorted' => true,
		'align' => true,
		'bgcolor' => true,
		'height' => true,
		'valign' => true,
		'width' => true,
	),
	'thead' => array(
	),
	'time' => array(
		'datetime' => true,
	),
	'title' => array(
		'class' => true,
	),
	'tr' => array(
		'align' => true,
		'bgcolor' => true,
		'height' => true,
		'valign' => true,
	),
	'track' => array(
	),
	'tref' => array(
		'class' => true,
		'externalresourcesrequired' => true,
	),
	'tspan' => array(
		'class' => true,
		'dx' => true,
		'dy' => true,
		'externalresourcesrequired' => true,
		'rotate' => true,
		'lengthadjust' => true,
		'textlength' => true,
		'x' => true,
		'y' => true,
	),
	'tt' => array(
	),
	'u' => array(
	),
	'ul' => array(
	),
	'use' => array(
		'class' => true,
		'externalresourcesrequired' => true,
		'height' => true,
		'transform' => true,
		'width' => true,
		'x' => true,
		'y' => true,
	),
	'var' => array(
	),
	'video' => array(
		'autoplay' => true,
		'controls' => true,
		'height' => true,
		'loop' => true,
		'muted' => true,
		'poster' => true,
		'preload' => true,
		'src' => true,
		'width' => true,
	),
	'view' => array(
		'externalresourcesrequired' => true,
		'preserveaspectratio' => true,
		'viewbox' => true,
		'viewtarget' => true,
		'zoomandpan' => true,
	),
	'vkern' => array(
		'g1' => true,
		'g2' => true,
		'k' => true,
		'u1' => true,
		'u2' => true,
	),
	'wbr' => array(
	),
	'xmp' => array(
	),
);

?>
