<?php
/**
 * Generated by amp_wp_build_styles.py - do not edit.
 *
 * This is a list of CSS attributes that are allowed by the
 * AMP specification.
 */
class AMP_Allowed_Styles_Generated {

	private static $spec_file_revision = 325;
	private static $minimum_validator_revision_required = 189;

	private static $allowed_styles = array(
		'style' => array(
			array(
				'attr_spec_list' => array(
					'amp-custom' => array(
						'mandatory' => true,
						'value' => '',
					),
					'type' => array(
						'value_casei' => 'text/css',
					),
				),
				'cdata_spec_list' => array(
					'blacklisted_cdata_regex' => array(
						'<!--',
						'\\.i?-amp-',
						'(^|\\W)i-amphtml-',
						'!important',
					),
					'css_spec' => array(
						'at_rule_spec' => array(
								'$default',
								'-moz-keyframes',
								'-o-keyframes',
								'-webkit-keyframes',
								'font-face',
								'keyframes',
								'media',
								'supports',
						),
						'font_url_spec' => array(
							'allow_empty' => true,
							'allow_relative' => true,
							'allowed_protocol' => array(
								'data',
								'http',
								'https',
							),
						),
						'image_url_spec' => array(
							'allow_empty' => true,
							'allow_relative' => true,
							'allowed_protocol' => array(
								'absolute',
								'data',
								'http',
								'https',
							),
						),
					),
					'max_bytes' => '50000',
					'max_bytes_spec_url' => 'https://www.ampproject.org/docs/reference/spec.html#maximum-size',
				),
				'tag_spec' => array(
					'html_format' => array(
						'amp',
					),
					'mandatory_parent' => 'head',
					'spec_name' => 'style amp-custom',
					'spec_url' => 'https://www.ampproject.org/docs/reference/spec.html#stylesheets',
					'unique' => true,
				),

			),
			array(
				'attr_spec_list' => array(
					'amp-custom' => array(
						'mandatory' => true,
						'value' => '',
					),
					'type' => array(
						'value_casei' => 'text/css',
					),
				),
				'cdata_spec_list' => array(
					'blacklisted_cdata_regex' => array(
						'<!--',
						'\\.i?-amp-',
						'(^|\\W)i-amphtml-',
						'!important',
					),
					'css_spec' => array(
						'at_rule_spec' => array(
								'$default',
								'-moz-keyframes',
								'-o-keyframes',
								'-webkit-keyframes',
								'font-face',
								'keyframes',
								'media',
								'supports',
						),
						'font_url_spec' => array(
							'allow_empty' => true,
							'allow_relative' => true,
							'allowed_protocol' => array(
								'data',
								'http',
								'https',
							),
						),
						'image_url_spec' => array(
							'allow_empty' => true,
							'allow_relative' => true,
							'allowed_protocol' => array(
								'absolute',
								'data',
								'http',
								'https',
							),
						),
					),
					'max_bytes' => '20000',
					'max_bytes_spec_url' => 'https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md#css',
				),
				'tag_spec' => array(
					'html_format' => array(
						'amp4ads',
					),
					'mandatory_parent' => 'head',
					'spec_name' => 'style amp-custom (amp4ads)',
					'spec_url' => 'https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md#css',
					'unique' => true,
				),

			),
			array(
				'attr_spec_list' => array(
					'amp-boilerplate' => array(
						'dispatch_key' => true,
						'mandatory' => true,
						'value' => '',
					),
				),
				'cdata_spec_list' => array(
					'cdata_regex' => '\\s*body{-webkit-animation:-amp-start\\s+8s\\s+steps\\(1,end\\)\\s+0s\\s+1\\s+normal\\s+both;-moz-animation:-amp-start\\s+8s\\s+steps\\(1,end\\)\\s+0s\\s+1\\s+normal\\s+both;-ms-animation:-amp-start\\s+8s\\s+steps\\(1,end\\)\\s+0s\\s+1\\s+normal\\s+both;animation:-amp-start\\s+8s\\s+steps\\(1,end\\)\\s+0s\\s+1\\s+normal\\s+both}@-webkit-keyframes\\s+-amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes\\s+-amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes\\s+-amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes\\s+-amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes\\s+-amp-start{from{visibility:hidden}to{visibility:visible}}\\s*',
				),
				'tag_spec' => array(
					'also_requires_tag' => array(
						'also_requires_tag' => array(
								'noscript > style[amp-boilerplate]',
						),
					),
					'html_format' => array(
						'amp',
					),
					'mandatory_alternatives' => 'head > style[amp-boilerplate]',
					'mandatory_parent' => 'head',
					'spec_name' => 'head > style[amp-boilerplate]',
					'spec_url' => 'https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md',
					'unique' => true,
				),

			),
			array(
				'attr_spec_list' => array(
					'amp4ads-boilerplate' => array(
						'dispatch_key' => true,
						'mandatory' => true,
						'value' => '',
					),
				),
				'cdata_spec_list' => array(
					'cdata_regex' => '\\s*body{visibility:hidden}\\s*',
				),
				'tag_spec' => array(
					'html_format' => array(
						'amp4ads',
					),
					'mandatory_parent' => 'head',
					'spec_name' => 'head > style[amp4ads-boilerplate]',
					'spec_url' => 'https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md#boilerplate',
					'unique' => true,
				),

			),
			array(
				'attr_spec_list' => array(
					'amp-boilerplate' => array(
						'dispatch_key' => true,
						'mandatory' => true,
						'value' => '',
					),
				),
				'cdata_spec_list' => array(
					'cdata_regex' => '\\s*body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}\\s*',
				),
				'tag_spec' => array(
					'also_requires_tag' => array(
						'also_requires_tag' => array(
								'head > style[amp-boilerplate]',
						),
					),
					'html_format' => array(
						'amp',
					),
					'mandatory_alternatives' => 'noscript > style[amp-boilerplate]',
					'mandatory_parent' => 'noscript',
					'spec_name' => 'noscript > style[amp-boilerplate]',
					'spec_url' => 'https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md',
					'unique' => true,
				),

			),
		),
	);
	public static function get_allowed_styles() {
		return self::$allowed_styles;
	}

	public static function get_custom_styles_for_amp_html() {
		foreach ( self::$allowed_styles['style'] as $value) {
			if ( isset( $value['attr_spec_list']['amp-custom'] ) &&
				in_array( 'amp', $value['tag_spec']['html_format'] ) ) {
				return $value;
			}
		}
	}

}

?>
