<?php
/**
 * Footer template part.
 *
 * 🚫🚫🚫
 * DO NOT EDIT THIS FILE WHILE INSIDE THE PLUGIN! Changes You make will be lost when a new version
 * of the AMP plugin is released. You need to copy this file out of the plugin and put it into your
 * custom theme, for example. To learn about how to customize these Reader-mode AMP templates, please
 * see: https://amp-wp.org/documentation/how-the-plugin-works/classic-templates/
 * 🚫🚫🚫
 *
 * @package AMP
 */

/**
 * Context.
 *
 * @var AMP_Post_Template $this
 */
?>
<footer class="amp-wp-footer">
	<div>
		<h2><?php echo esc_html( wptexturize( $this->get( 'blog_name' ) ) ); ?></h2>
		<a href="#top" class="back-to-top"><?php esc_html_e( 'Back to top', 'amp' ); ?></a>
	</div>

	<?php $canonical_link_url = $this->get( 'post_canonical_link_url' ); ?>
	<?php if ( $canonical_link_url ) : ?>
		<?php $canonical_link_text = $this->get( 'post_canonical_link_text' ); ?>
		<div id="site-version-switcher">
			<a
					id="version-switch-link"
					rel="noamphtml"
					href="<?php echo esc_url( $canonical_link_url ); ?>"
			>
				<?php echo esc_html( $canonical_link_text ); ?>
			</a>
		</div>
	<?php endif; ?>
</footer>
