<?php
/**
 * HTML end template part.
 *
 * 🚫🚫🚫
 * DO NOT EDIT THIS FILE WHILE INSIDE THE PLUGIN! Changes You make will be lost when a new version
 * of the AMP plugin is released. You need to copy this file out of the plugin and put it into your
 * custom theme, for example. To learn about how to customize these Reader-mode AMP templates, please
 * see: https://amp-wp.org/documentation/how-the-plugin-works/classic-templates/
 * 🚫🚫🚫
 *
 * @package AMP
 */

/**
 * Context.
 *
 * @var AMP_Post_Template $this
 */
?>

<?php
/**
 * Fires just before printing the </body> closing tag.
 *
 * @since 0.2
 * @see wp_footer()
 *
 * @param AMP_Post_Template $this
 */
do_action( 'amp_post_template_footer', $this );
?>

</body>
</html>
